### ISSUE TITLE
Little Mistake on the french version 

### ISSUE THREAD

**Issue by Dentesk** [MicrosoftDocs/azure-docs.fr-fr#108]
AMSClientId : ID client d’application Azure AD.
AMSClientId : clé secrète client d’application Azure AD. => Should be "AMSClientSecret : clé secrète client d’application Azure AD."

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b739ea16-5477-9809-a4b6-bf938852ea22
* Version Independent ID: 62079614-c541-a3ed-3054-141c8e1dd4ff
* Content: [Développement de fonctions Azure Functions avec Media Services](https://docs.microsoft.com/fr-fr/azure/media-services/previous/media-services-dotnet-how-to-use-azure-functions)
* Content Source: [articles/media-services/previous/media-services-dotnet-how-to-use-azure-functions.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/media-services/previous/media-services-dotnet-how-to-use-azure-functions.md)
* Service: **media-services**
* GitHub Login: @Juliako
* Microsoft Alias: **juliako**

**Comment by DavidPrio** [comment]
Hello, @Dentesk ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @Dentesk 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/media-services/previous/media-services-dotnet-how-to-use-azure-functions 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
