### ISSUE TITLE
Traduction incorrecte

### ISSUE THREAD

**Issue by lmazuel** [MicrosoftDocs/azure-docs.fr-fr#13]
Bonjour,

Pour cet article: https://github.com/Microsoft/azure-docs.fr-fr/blob/master/articles/monitoring-and-diagnostics/monitoring-supported-metrics.md

La traduction est incorrecte. La première colonne "Mesure" est une colonne technique, dans le nom doit être utilisé dans les appels HTTP pour Azure. Elle ne doit **pas** être traduite. Cela semble évident pour Batch avec des noms tel que `TotalNodeCount`, moins pour Compute car les noms techniques sont traduisibles, mais c'est le cas dans toutes les situations.

(Je travaille à MS Redmond dans l'équipe Azure SDK, mais je suis français alors j'en profite pour relire les docs traduites :))

**Comment by SunnyDeng** [comment]
hasn't fixed. Move to the new bug system https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8438.

**Comment by SunnyDeng** [comment]
@lmazuel we fixed in translation memory. Thanks for your contribution. 
If you see repro, please feel free to re-open this issue.
