### ISSUE TITLE
translation for 'Contributor'

### ISSUE THREAD

**Issue by shenhuiying2017** [MicrosoftDocs/azure-docs.fr-fr#137]
The correct translation of contributor is contributeur instead of collaborateur. In this article, 'Contributeur' and 'Collaborateur' are both used in many places. No coherence. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 69c4b0e0-a13e-12be-dcf8-263d81c90ab5
* Version Independent ID: f164301d-63ec-cca1-e0c9-2aae5849b97c
* Content: [Rôles intégrés pour le contrôle d’accès en fonction du rôle (RBAC) dans Azure](https://docs.microsoft.com/fr-fr/azure/role-based-access-control/built-in-roles)
* Content Source: [articles/role-based-access-control/built-in-roles.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/role-based-access-control/built-in-roles.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by gosali** [comment]
Hello, @shenhuiying2017,   

Thank you for your feedback. 

  
We are actively reviewing your comments and will get back to you soon. 

 
Kind regards, 

Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @shenhuiying2017 ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/role-based-access-control/built-in-roles.  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
