### ISSUE TITLE
What is the minimum role needed to read the log stream of an App Service?

### ISSUE THREAD

**Issue by nouvel-r** [MicrosoftDocs/azure-docs.fr-fr#151]
What is the minimum role needed to read the log stream of an App Service?

We'd like to give some of our developers the ability to read the log stream of a Production App Service without having them to be contributors to the App Service.

Is it possible? If so then what is the mimimum role to give them?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 46653d6e-d057-e698-ef94-32d48e12d39f
* Version Independent ID: 74beaf3c-60f9-006d-110a-fbe2348d4797
* Content: [Activer la journalisation des diagnostics pour les applications web dans Azure App Service](https://docs.microsoft.com/fr-fr/azure/app-service/web-sites-enable-diagnostic-log)
* Content Source: [articles/app-service/web-sites-enable-diagnostic-log.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/app-service/web-sites-enable-diagnostic-log.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by gosali** [comment]
Hello, @nouvel-r , 

 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

 

Kind regards, 

Microsoft DOCS International Team

**Comment by SunnyDeng** [comment]
Yes, @nouvel-r, this is the question that dev or feature PM to answer, please file to Production team using 'Give Product Feedback' button (left side of 'Content Feedback').
