### ISSUE TITLE
Mauvaise traduction MBps se traduit pas par Mbits/s

### ISSUE THREAD

**Issue by julien-padovani** [MicrosoftDocs/azure-docs.fr-fr#159]
MBps a été traduit par Mbits. La traduction correcte en français c'est Mo. 
1 MB = 1 Mo = 8 Mb (respectivement MegaBytes, MégaOctets, Megabits)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 58fe6a40-0b95-f1ed-db11-7a49d4a97ecf
* Version Independent ID: 54269236-da55-a1cd-01df-79a0458d9ac9
* Content: [Tailles des machines virtuelles Azure Windows - Mémoire](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/sizes-memory#feedback)
* Content Source: [articles/virtual-machines/windows/sizes-memory.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/virtual-machines/windows/sizes-memory.md)
* Service: **virtual-machines-windows**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by gosali** [comment]
Bonjour, @julien-padovani ,  

Merci pour votre feedback.  
 
Nous révisons activement vos commentaires et nous vous recontacterons bientôt.  
 
Cordialement,  

L’équipe Microsoft DOCS International

**Comment by LisandroSu** [comment]
Bonjour @julien

Merci pour vos   suggestions linguistiques.
 
Malheureusement, après   révision, notre équipe linguistique a jugé qu’elles ne remplissaient pas nos   critères de validation, car ne suit pas les guides de style de Microsoft
 
Votre contribution à nos   articles est grandement appréciée. Nous vous encourageons donc à continuer   d’envoyer vos commentaires à Microsoft.
 
Cordialement,
 
L’équipe Microsoft DOCS   International

**Comment by julien** [comment]
wrong julien :)

**Comment by julien-padovani** [comment]
Hello,

Je ne comprends pas. En quoi mon commentaire n'est pas validé ?

Il faut réviser les bases ! 
MB, c'est Megabyte (en anglais), égal à 8 Mb
MO ou Mo, c'est MegaOctet (enfin francais), égal à 8Mb
Mb, c'est Megabit (anglais ou français)

Donc votre traduction 1MB = 1Mb est fausse
