### ISSUE TITLE
Developer

### ISSUE THREAD

**Issue by gauger123** [MicrosoftDocs/azure-docs.fr-fr#160]
Bonjour,

L'exemple ne fonctionne pas. Après avoir cliqué sur le bouton j'obtiens:
--------------------
Error: "OpenIdConnectMessage.Error was not null, indicating an error. Error: 'access_denied'. Error_Description (may be empty): 'AADSTS65005: Using application 'WebApp' is currently not supported for your organization domedic.ca because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of domedic.ca before the application WebApp can be provisioned. Trace ID: 42ab5c37-9061-47c0-88c7-9ae9ca830500 Correlation ID: e999784a-eb03-4231-81a5-7f9c656e7841 Timestamp: 2018-07-04 15:34:27Z'. Error_Uri (may be empty): ''."
--------------------
J'ai créé une application dans Azure de type "Native" puis refait le test avec une autre de type "Application/Web API". J'obtiens le même message. J'ai fait le test avec le projet déjà monté puis passé à la configuration comme prescrit. J'ai également testé en créant tout les fichiers en suivant la procédure.
Je doute que l'on doit conserver une redirection "localhost" pour un déploiement dans Azure...

Avez-vous une idée du problème?

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 768d0a46-3c55-33e2-630e-075e9b624e3b
* Version Independent ID: 715cd56e-54cb-478c-a3b1-2416e1e18643
* Content: [Bien démarrer avec le serveur web ASP.NET Azure AD v1](https://docs.microsoft.com/fr-ca/azure/active-directory/develop/guidedsetups/active-directory-aspnetwebapp-v1#configure-your-webconfig-and-register-an-application)
* Content Source: [articles/active-directory/develop/GuidedSetups/active-directory-aspnetwebapp-v1.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/active-directory/develop/GuidedSetups/active-directory-aspnetwebapp-v1.md)
* Service: **active-directory**
* GitHub Login: @andretms
* Microsoft Alias: **andret**

**Comment by gosali** [comment]
Bonjour @gauger123 ,  

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation.  

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs.  
Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal.  
@SunnyDeng 
Votre contribution à nos articles est grandement appréciée.   

Cordialement,  

L’équipe Microsoft DOCS International
