### ISSUE TITLE
Pages FR-FR et EN-US ne correspondent pas

### ISSUE THREAD

**Issue by YBoutemy** [MicrosoftDocs/azure-docs.fr-fr#162]
Bonjour,
La page FR-FR ne correspond manifestement pas à la page EN-US dont elle est censée être la traduction.
Merci. Cordialement,
Yves Boutemy.
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5427bd36-c76c-8a47-e91d-1e75af36ee01
* Version Independent ID: 4074b64b-adc2-1a53-8fd6-5749308ce260
* Content: [Gérer l’accès et les autorisations avec le contrôle d’accès en fonction du rôle (RBAC) - Azure RBAC](https://docs.microsoft.com/fr-fr/azure/role-based-access-control/overview)
* Content Source: [articles/role-based-access-control/overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/role-based-access-control/overview.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by DavidPrio** [comment]
Bonjour, @YBoutemy , 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by LisandroSu** [comment]
Bonjour, @YBoutemy ,

Merci pour votre feedback. 

Notre équipe d’ingénieurs a révisé vos suggestions et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/role-based-access-control/overview du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
