### ISSUE TITLE
Pages FR-FR et EN-US ne correspondent pas

### ISSUE THREAD

**Issue by YBoutemy** [MicrosoftDocs/azure-docs.fr-fr#163]
Bonjour,
La page FR-FR ne correspond manifestement pas à la page EN-US dont elle est censée être la traduction.
Merci. Cordialement,
Yves Boutemy.
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 3deb77d4-07ed-feeb-2a80-cb5fe5a39b9d
* Version Independent ID: 4a292cfd-6d08-5e22-8900-843b9347187e
* Content: [Présentation de l’accès aux ressources dans Azure](https://docs.microsoft.com/fr-fr/azure/role-based-access-control/rbac-and-directory-admin-roles)
* Content Source: [articles/role-based-access-control/rbac-and-directory-admin-roles.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/role-based-access-control/rbac-and-directory-admin-roles.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by DavidPrio** [comment]
Bonjour, @YBoutemy , 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by LisandroSu** [comment]
Bonjour, @YBoutemy ,

Merci pour votre feedback.

Notre équipe d’ingénieurs a révisé vos suggestions et les a acceptées. Nous avons modifié les articles   concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/role-based-access-control/rbac-and-directory-admin-roles du site Docs.
 
Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer   d’envoyer vos commentaires à Microsoft.

Cordialement,
L’équipe Microsoft DOCS   International
