### ISSUE TITLE
Issue with Docker

### ISSUE THREAD

**Issue by HommeViande** [MicrosoftDocs/azure-docs.fr-fr#165]
Hi,

I followed this tutorial step by step but find myself blocked when trying to build the IoT Edge Solution.
The login works fine, I didn't change anything on the second step as my Edge Device is a virtual machine running on Ubuntu 16.04 64bit
I added the username and the password of my container in the .env file, then the module twin in the deployment manifest, even saved the file.

Then I clicked on "Build the IoT Edge Solution" as indicated, but the command generated didn't work.
At first it was because of the permissions so I added sudo before both docker instructions of the command.
The docker build seems to work but the docker push makes an error :

$ sudo docker push edgecontainer.azurecr.io:0.0.1-amd64
The push refers to repository [docker.io/library/&lt;my container&gt;.azurecr.io]
a0f4baaa2284: Preparing
76d43953facc: Preparing
308f5da9bb87: Preparing
96d34cb80eb6: Preparing
c5a11fc258f4: Preparing
bbe892a9c337: Waiting
a2e66f6c6f5f: Waiting
denied: requested access to the resource is denied

Though I don't think it is related in any way to my configuration, my OS is Ubuntu 16.04 64bit and I use VSCode 1.22.2

Thank you in advance for helping me in finding what is wrong with what I did.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 181d5562-f8d7-9c59-85ea-09efbe397f3e
* Version Independent ID: dbedd952-a050-286e-c951-4529ec8e87b8
* Content: [Tutoriel C# d’Azure IoT Edge](https://docs.microsoft.com/fr-fr/azure/iot-edge/tutorial-csharp-module)
* Content Source: [articles/iot-edge/tutorial-csharp-module.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/iot-edge/tutorial-csharp-module.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by DavidPrio** [comment]
Hello, @HommeViande  ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.
Kind regards,
Microsoft DOCS International Team

Hi @SunnyDeng  can you please investigate internally if this is Source Documentation issue or a product issue? Thanks!

**Comment by kgremban** [comment]
@HommeViande Are you using a Docker container registry or an Azure container registry? The repository address in the push command looks strange: **docker.io/library/<my container>.azurecr.io**.

I'm not sure about the syntax if you're pushing to Docker, but for Azure it should look like <my container registry>.azurecr.io/<my module name>. This is the repository address that you declare in step 4.e in https://docs.microsoft.com/azure/iot-edge/tutorial-csharp-module#create-an-iot-edge-module-project
