### ISSUE TITLE
chrome://media-router/

### ISSUE THREAD

**Issue by AvatarWeb1** [MicrosoftDocs/azure-docs.fr-fr#166]
chrome://media-router/

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4cff90b4-ed1e-5069-7863-2308911e80e5
* Version Independent ID: e3e9842e-349b-7dd4-2b63-dc47a2ec0b56
* Content: [Réseaux virtuels et machines virtuelles Windows dans Azure](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/network-overview)
* Content Source: [articles/virtual-machines/windows/network-overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/virtual-machines/windows/network-overview.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by gosali** [comment]
Hello, @AvatarWeb1 ,   

Thank you for your feedback.  
We are actively reviewing your comments and will get back to you soon. 

Could please provide further clarification about this issue?

Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @AvatarWeb1 ,  

Thank you for your feedback.
We are actively reviewing your comments and will get back to you soon.

Could please provide further clarification about this issue?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @AvatarWeb1 
We don't have enough information to work on this issue so we'll close it.

If the issue persists, you are welcome to open a new one.

Kind regards,
Microsoft DOCS International Team
