### ISSUE TITLE
Lien "Centre pour développeurs PHP" 404

### ISSUE THREAD

**Issue by xavierrouhaud** [MicrosoftDocs/azure-docs.fr-fr#170]
ce lien n'est plus fonctionnel : Centre pour développeurs PHP (https://docs.microsoft.com/fr-fr/develop/php/)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5e564777-8d59-9065-6f0d-d8ea3fc6ee62
* Version Independent ID: ec93756c-4d7f-efc8-a8ca-9b87d1be8ac3
* Content: [Configurer PHP dans Azure App Service Web Apps](https://docs.microsoft.com/fr-fr/azure/app-service/web-sites-php-configure)
* Content Source: [articles/app-service/web-sites-php-configure.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/app-service/web-sites-php-configure.md)
* Service: **app-service**
* GitHub Login: @msangapu
* Microsoft Alias: **msangapu**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #12308](https://github.com/MicrosoftDocs/azure-docs/issues/12308) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Bonjour @xavierrouhaud ,
 
Merci pour votre contribution.   Votre feedback porte sur la documentation en langue anglaise.
 
Nous l’avons donc transféré au   dépôt Anglais. Vous pouvez consulter le statut de votre demande ici :   https://github.com/MicrosoftDocs/azure-docs/issues/12308. 
 
Votre contribution à nos   articles est grandement appréciée.
  
Cordialement,
 
L’équipe Microsoft DOCS   International
