### ISSUE TITLE
web app not working 

### ISSUE THREAD

**Issue by agostinia** [MicrosoftDocs/azure-docs.fr-fr#171]
The nodejs web app was not working for me until I changed the node version used by the webapp to "8.1.4" by going in "Application settings" and changing WEBSITE_NODE_DEFAULT_VERSION key from "6.9.1" to "8.1.4".

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 681e10a1-05d3-5761-2afd-42602a7efecf
* Version Independent ID: f72e21b1-3530-8554-f1f1-fc66b222a485
* Content: [Visualisation en temps réel de données de capteur à partir de votre Azure IoT Hub – Web Apps](https://docs.microsoft.com/fr-fr/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps)
* Content Source: [articles/iot-hub/iot-hub-live-data-visualization-in-web-apps.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/iot-hub/iot-hub-live-data-visualization-in-web-apps.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by LisandroSu** [comment]
Hello, @agostinia , 
 
Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 
 
If you have any feedback related to the documentation, please feel free to log it through this channel. 
We truly appreciate your contribution to our articles.  
 
Kind regards, 
Microsoft DOCS International Team
