### ISSUE TITLE
Alternatives aux Workbench ?

### ISSUE THREAD

**Issue by Babishula** [MicrosoftDocs/azure-docs.fr-fr#175]
Je n'ai pas Windows 10 sur mon ordinateur. J'aimerai savoir s'il existe une autre façon d'utiliser Azure ML.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 089419cb-c22f-ca1a-fd06-a8f18c05c1da
* Version Independent ID: f53bf992-45d1-4e87-e8c9-caffbb2b15ee
* Content: [Guide de démarrage rapide pour installer les services Azure Machine Learning](https://docs.microsoft.com/fr-fr/azure/machine-learning/service/quickstart-installation#prerequisites)
* Content Source: [articles/machine-learning/service/quickstart-installation.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/machine-learning/service/quickstart-installation.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by gosali** [comment]
Bonjour @Babishula ,  

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation.  
Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs.  

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal.  
Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
