### ISSUE TITLE
Update ComputerVisionAPI according to Nuget Package

### ISSUE THREAD

**Issue by CoRouff** [MicrosoftDocs/azure-docs.fr-fr#177]
Please update the program.cs code to reflect the updated version of the Nuget package.
The given sample code is out of date and the class ComputerVisionAPI must be replaced by ComputerVisionClient.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 52fd1d7a-6670-a3f3-40f7-350ba7e31a14
* Version Independent ID: f5d51702-e86d-4442-8658-8a2df670d51a
* Content: [API Vision par ordinateur avec C# - Démarrage rapide : SDK, analyse d’image - Microsoft Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/Computer-vision/quickstarts-sdk/csharp-analyze-sdk)
* Content Source: [articles/cognitive-services/Computer-vision/quickstarts-sdk/csharp-analyze-sdk.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/cognitive-services/Computer-vision/quickstarts-sdk/csharp-analyze-sdk.md)
* Service: **cognitive-services**
* GitHub Login: @noellelacharite
* Microsoft Alias: **v-deken**

**Comment by LisandroSu** [comment]
Hello, @CoRouff 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @CoRouff
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/cognitive-services/Computer-vision/quickstarts-sdk/csharp-analyze-sdk. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
