### ISSUE TITLE
Prérequis VS et .Net

### ISSUE THREAD

**Issue by mflpb** [MicrosoftDocs/azure-docs.fr-fr#190]
Bonjour,
J'aimerais savoir si Visual Studio 2017 est un prérequis ou si on peut utiliser une version de Visual Studio antérieur ?

Il y a t-il une version spécifique du framework .Net en prérequis ? 

Merci d'avance,
Cordialement

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a0c01253-54e1-02da-e7f5-3be6bfbf2294
* Version Independent ID: 27dd48d8-d829-79ec-a5f8-b7dae2855aa1
* Content: [Démarrage rapide : Reconnaissance vocale en C# sous .NET Framework sur Windows à l’aide du kit SDK Speech de Cognitive Services - Microsoft Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/speech-service/quickstart-csharp-dotnet-windows)
* Content Source: [articles/cognitive-services/Speech-Service/quickstart-csharp-dotnet-windows.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/cognitive-services/Speech-Service/quickstart-csharp-dotnet-windows.md)
* Service: **cognitive-services**
* GitHub Login: @wolfma61
* Microsoft Alias: **wolfma**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17540](https://github.com/MicrosoftDocs/azure-docs/issues/17540) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Bonjour @mflpb , 

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/17540. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
