### ISSUE TITLE
Wrong sample code in french translated version 

### ISSUE THREAD

**Issue by AleksCallebat** [MicrosoftDocs/azure-docs.fr-fr#195]
Those are the urls with which I get the bug :

https://docs.microsoft.com/fr-fr/azure/cognitive-services/custom-vision-service/python-tutorial
https://docs.microsoft.com/en-us/azure/cognitive-services/Custom-Vision-Service/python-tutorial

As you can see, the french version calls for a method _training_api_ which seems obsolete (in Image classification it is not defined, in object detection it does an import that doesn't exist). The samples in the english version seem fine.

I believe it raises a question as to how the doc is translated (why would the code change??).

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 646cbb8a-041e-9d99-0385-272f31793552
* Version Independent ID: b9ae4376-2e8f-f311-8b1b-d4e3120bf5b5
* Content: [Guide de démarrage rapide : créer un projet de classification d’images à l’aide du kit de développement logiciel (SDK) Vision personnalisée pour Python](https://docs.microsoft.com/fr-fr/azure/cognitive-services/custom-vision-service/python-tutorial)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/python-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/cognitive-services/Custom-Vision-Service/python-tutorial.md)
* Service: **cognitive-services**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by CeciAc** [comment]
Hello, @AleksCallebat 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by areddish** [comment]
Thanks @AleksCallebat , looks like image classification wasn't updated. I've submitted a PR to correct the wrong client name.

**Comment by CeciAc** [comment]
Hello, @AleksCallebat
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @AleksCallebat 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/cognitive-services/custom-vision-service/python-tutorial. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
