### ISSUE TITLE
BCP  Error: Unknown argument -S

### ISSUE THREAD

**Issue by lblanche** [MicrosoftDocs/azure-docs.fr-fr#200]
Hello I am trying to use bcp from a data science VM to upload data into an Azure SQL Database, however I get this output, like if -S was not an option :

Error: Unknown argument -S
Usage:
   bcp --list [options] module-list
   bcp --list-short [options] module-list
   bcp --report [options] module-list html-file
   bcp [options] module-list output-path

Options:
   --boost=path     sets the location of the boost tree to path
   --scan           treat the module list as a list of (possibly non-boost)
                    files to scan for boost dependencies
   --svn            only copy files under cvs version control
   --unix-lines     make sure that all copied files use Unix style line endings
   --namespace=name rename the boost namespace to name (also changes library names).
   --namespace-alias Makes namespace boost an alias of the namespace set with --namespace.

module-list:         a list of boost files or library names to copy
html-file:           the name of a html file to which the report will be written
output-path:         the path to which files will be copied

if i try :  man -k bcp  

I get this : 

bcp (1)              - extract subsets of Boost

I am unsure wether the bcp installed on the Azure DS VM is the bcp used in this tutorial ..

Any help would be appreciated :)
Thanks 
Luis

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2d10956a-5e04-e36e-4525-68850678a7ef
* Version Independent ID: 572cdda2-f855-01e4-dfea-989dd3b0c3d0
* Content: [Charger des données à partir d’un fichier CSV dans la base de données SQL Azure (BCP)](https://docs.microsoft.com/fr-fr/azure/sql-database/sql-database-load-from-csv-with-bcp)
* Content Source: [articles/sql-database/sql-database-load-from-csv-with-bcp.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/sql-database/sql-database-load-from-csv-with-bcp.md)
* Service: **sql-database**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CeciAc** [comment]
Hello, @lblanche 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
