### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by ThierryBT** [MicrosoftDocs/azure-docs.fr-fr#210]
Hi and sorry for my Funny English.
I see an error in translation for this document.
https://docs.microsoft.com/en-us/azure/load-balancer/quickstart-create-basic-load-balancer-portal
In English
Create a load balancer rule
A load balancer rule defines how traffic is distributed to the VMs. The rule defines the front-end IP configuration for incoming traffic, the back-end IP pool to receive the traffic, and the required source and destination ports. 

In French, 
https://docs.microsoft.com/fr-fr/azure/load-balancer/quickstart-create-basic-load-balancer-portal
Créer une règle d’équilibreur de charge
Une règle d’équilibreur de charge définit la distribution du trafic vers les machines virtuelles. La règle définit la configuration IP front-end pour le trafic entrant, le pool d’adresses IP front-end pour recevoir le trafic ainsi que les ports source et de destination nécessaires.

The error is "le pool d’adresses IP front-end pour recevoir le trafic" (Is not Front, but back-end).
The good translation is =&gt; "le pool d’adresses IP BACK-END pour recevoir le trafic" (the back-end IP pool to receive the traffic).

Regards 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: af871177-05e5-4194-bbb1-69d765c475c2
* Version Independent ID: a4ed57d6-3d56-bf1d-1f72-c81b00556960
* Content: [Démarrage rapide : Créer un équilibreur de charge de base public à l’aide du portail Azure](https://docs.microsoft.com/fr-fr/azure/load-balancer/quickstart-create-basic-load-balancer-portal)
* Content Source: [articles/load-balancer/quickstart-create-basic-load-balancer-portal.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/load-balancer/quickstart-create-basic-load-balancer-portal.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by CeciAc** [comment]
Hello, @ThierryBT 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ThierryBT** [comment]
Thanks  ;)

**Comment by CeciAc** [comment]
Hello, @ThierryBT 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/load-balancer/quickstart-create-basic-load-balancer-portal. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by ThierryBT** [comment]
Thank you Cecilia !
