### ISSUE TITLE
Error in translation

### ISSUE THREAD

**Issue by ThierryBT** [MicrosoftDocs/azure-docs.fr-fr#234]
Hi and sorry for my Funny English.
I see an error in translation for this document.
https://docs.microsoft.com/en-us/azure/virtual-network/tutorial-create-route-table-portal
In English, chapter Turn on IP forwarding within myVmNva, point 5.In the Remote Desktop of myVmPublic, open PowerShell.
You must launch New-NetFirewallRule –DisplayName “Allow ICMPv4-In” –Protocol ICMPv4

In French, chapter Activer le transfert IP dans myVmNva, point 5.Dans le Bureau à distance de myVmPrivate, ouvrez PowerShell.
You must launch New-NetFirewallRule –DisplayName “Allow ICMPv4-In” –Protocol ICMPv4
But the command must be launched on the machine myVmPublic, not in myVmPrivate.

Regards

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 5cc61595-d1ea-d72b-bef8-52e7b7838a14
* Version Independent ID: 6df6127e-bf72-eb63-82c2-a132a6576add
* Content: [Acheminer le trafic réseau - Didacticiel - Portail Azure](https://docs.microsoft.com/fr-fr/azure/virtual-network/tutorial-create-route-table-portal)
* Content Source: [articles/virtual-network/tutorial-create-route-table-portal.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/virtual-network/tutorial-create-route-table-portal.md)
* Service: **virtual-network**
* GitHub Login: @jimdial
* Microsoft Alias: **jdial**

**Comment by ThierryBT** [comment]
Hi,
The screen with error :
![image](https://user-images.githubusercontent.com/28751337/50822659-87d9c800-1332-11e9-96b1-b3ab9b2c1fde.png)

**Comment by CeciAc** [comment]
Hello, @ThierryBT
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ThierryBT 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/virtual-network/tutorial-create-route-table-portal. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by ThierryBT** [comment]
Thank you Cecilia !
