### ISSUE TITLE
7. Vous pouvez supprimer une règle d’alerte de métrique à l’aide de la commande suivante.

### ISSUE THREAD

**Issue by Tezig** [MicrosoftDocs/azure-docs.fr-fr#235]
mauvaise commande pour ce cas de figure, la commande de supression est "delete et non "update" comme écrit pour l'instant

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0728f6aa-4933-e227-58c1-da28b3b6dd3f
* Version Independent ID: e8245931-ed83-cf3d-0c03-fcde025f41b6
* Content: [Créer, afficher et gérer des alertes de métrique à l’aide d’Azure Monitor](https://docs.microsoft.com/fr-fr/azure/azure-monitor/platform/alerts-metric)
* Content Source: [articles/azure-monitor/platform/alerts-metric.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/azure-monitor/platform/alerts-metric.md)
* Service: **azure-monitor**
* GitHub Login: @snehithm
* Microsoft Alias: **snmuvva**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21885](https://github.com/MicrosoftDocs/azure-docs/issues/21885) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Bonjour @Tezig 

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/21885. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
