### ISSUE TITLE
Customers wish to use their corporate Office 365 account how can we configure this?

### ISSUE THREAD

**Issue by lerouxe** [MicrosoftDocs/azure-docs.fr-fr#288]
Hi,
I see this restriction:
"SSO to customer owned apps within the Azure AD B2C tenants is supported. SSO to Office 365 or to other Microsoft and non-Microsoft SaaS apps is not supported."
The feedback we have indicates our customer would prefer to use their corporate O365 (whe they have one) account instead of creating yet another account/password local to our application. Is there a workaround for that?
Thanks,
ErC.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1b99765d-5ff4-56bf-fbd1-3a5f281f90da
* Version Independent ID: 053fdf19-73bb-4aba-ac18-e3cdae83861f
* Content: [Comparer B2B Collaboration et B2C dans Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/b2b/compare-with-b2c)
* Content Source: [articles/active-directory/b2b/compare-with-b2c.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/active-directory/b2b/compare-with-b2c.md)
* Service: **active-directory**
* GitHub Login: @msmimart
* Microsoft Alias: **mimart**

**Comment by LisandroSu** [comment]
Hello, @lerouxe 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
