### ISSUE TITLE
Inconsistent French translations for (azure) "label"

### ISSUE THREAD

**Issue by brunolewin-msft** [MicrosoftDocs/azure-docs.fr-fr#289]
Inconsistent French translations for (azure) "label": "balise" v/s "étiquette"

E.g. the title of this topic is using "balise" ("Organisation des ressources Azure à l’aide de balises") while most other areas including body, TOC and Portal use "étiquettes".

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bc003943-8bc8-10ac-e633-5640cff3c397
* Version Independent ID: f8826361-f601-acf9-3e3d-c96579c02093
* Content: [Organisation logique des ressources Azure à l’aide de balises](https://docs.microsoft.com/fr-fr/azure/azure-resource-manager/resource-group-using-tags)
* Content Source: [articles/azure-resource-manager/resource-group-using-tags.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/azure-resource-manager/resource-group-using-tags.md)
* Service: **azure-resource-manager**
* GitHub Login: @tfitzmac
* Microsoft Alias: **tomfitz**

**Comment by LisandroSu** [comment]
Hello, @brunolewin-msft 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @brunolewin-msft 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/azure-resource-manager/resource-group-using-tags

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
