### ISSUE TITLE
“run command” is mistranslated

### ISSUE THREAD

**Issue by brunolewin-msft** [MicrosoftDocs/azure-docs.fr-fr#298]
Hi - “run command” means “run a command” here but has been been mistranslated as “the ‘run’ command” throughout the article - see also internal Feedback 63685. Thanks!

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b3ff94e6-3c1f-b9e1-1a46-b75fe2ffca1b
* Version Independent ID: 8f3ca735-ddd4-f4a9-4ee0-189604018784
* Content: [Exécuter des scripts PowerShell dans une machine virtuelle Windows dans Azure](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/run-command)
* Content Source: [articles/virtual-machines/windows/run-command.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/virtual-machines/windows/run-command.md)
* Service: **automation**
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by CeciAc** [comment]
Hello, @brunolewin-msft 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @brunolewin-msft 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/run-command

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
