### ISSUE TITLE
Classification multi classes et label

### ISSUE THREAD

**Issue by Oz-teric** [MicrosoftDocs/azure-docs.fr-fr#299]
Bonjour, je me pose des questions pour la classification multi classes et plus particulièrement sur l'étiquetage des labels.
Si on choisit X = 15 la période précédant l'arrivée d'une défaillance pour un cas de figure binaire où l'erreur arrive au bout de 50 cycles, alors les cycles 36 à 50 auront le label défaillance, ça j'ai bien compris.
Cependant dans le cas multiclasses je me pose quelques questions. Par exemple, prenons une défaillance de type 1 au bout de 50 cycles, et une défaillance de type 2 au bout de 55 cycles, qui seront donc toutes les deux labelisées 1 et 2.
Comment procède-on ? En effet on est dans une situation où au cycle 45, une défaillance de type 1 arrivera dans les 15 prochains cycles, néanmoins c'est également le cas pour la défaillance de type 2.
Quelle étiquette appliquer, étiquette 1 ou étiquette 2 ?

Merci d'avance ! 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d464be99-8698-32d2-e0be-a971279614f5
* Version Independent ID: 089635f2-41b6-463a-8a07-90e7cda3c8d1
* Content: [Guide Azure AI pour les solutions de maintenance prédictive - Team Data Science Process](https://docs.microsoft.com/fr-fr/azure/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance#Data-requirements-for-predictive-maintenance)
* Content Source: [articles/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/machine-learning/team-data-science-process/cortana-analytics-playbook-predictive-maintenance.md)
* Service: **machine-learning**
* GitHub Login: @marktab
* Microsoft Alias: **tdsp**

**Comment by CeciAc** [comment]
Bonjour @Oz-teric 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
