### ISSUE TITLE
Référence à Azure Stack plutôt qu'Azure Status

### ISSUE THREAD

**Issue by sebclaude** [MicrosoftDocs/azure-docs.fr-fr#301]
Bonjour,
Dans la traduction français, la documentation fait référence à Azure Stack dans les titres plutôt qu'à Azure Status

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: bb7d1f73-bfb0-fd4f-4dfe-cad545467a35
* Version Independent ID: e56e646d-0067-26ad-b49c-cbe7623f050f
* Content: [Vue d’ensemble de l’état Azure](https://docs.microsoft.com/fr-fr/azure/service-health/azure-status-overview)
* Content Source: [articles/service-health/azure-status-overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/service-health/azure-status-overview.md)
* Service: **service-health**
* GitHub Login: @stephbaron
* Microsoft Alias: **stbaron**

**Comment by CeciAc** [comment]
Bonjour, @sebclaude 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
Bonjour @sebclaude 

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/service-health/azure-status-overview du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
