### ISSUE TITLE
[URGENT] Unable to cast object of type 'System.String' to type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext'

### ISSUE THREAD

**Issue by magaudef** [MicrosoftDocs/azure-docs.fr-fr#304]
Got this error when following the tutorial (got the same error when creating the function app from the Azure portal directly)
Here is the error:
"2019-03-21T15:56:07.651 [Error] Executed 'Functions.OrchestratorFunction' (Failed, Id=8a1f0994-536f-4b00-a47e-96bc050e0f4d)
Unable to cast object of type 'System.String' to type 'Microsoft.Azure.WebJobs.DurableOrchestrationContext'."

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7bc8fe9b-d51f-7858-8989-c37699a98a62
* Version Independent ID: b170803b-7bdc-b169-d76a-b0dd418ba629
* Content: [Créer votre première fonction durable dans Azure à l’aide de JavaScript](https://docs.microsoft.com/fr-fr/azure/azure-functions/durable/quickstart-js-vscode#feedback)
* Content Source: [articles/azure-functions/durable/quickstart-js-vscode.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/azure-functions/durable/quickstart-js-vscode.md)
* Service: **azure-functions**
* GitHub Login: @ColbyTresness
* Microsoft Alias: **azfuncdf, cotresne, glenga**

**Comment by CeciAc** [comment]
Hello, @magaudef 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
