### ISSUE TITLE
Issue with Salesforce connector on CaseHistory records

### ISSUE THREAD

**Issue by ThomasDebacker** [MicrosoftDocs/azure-docs.fr-fr#305]
Hello,

I want to copy every records from Case History in a storage account in Azure.
Everything works well except the fact that I don't get all the records. When values on Case's descriptions are changed, the record (that is created regarding this change) doesn't show up in my Azure storage.

I checked the Salesforce's profil and it seems to be correctly set (I have rights to read Case and Case's fields that are historised).

Do you have any clue why I can't import these records? Would it be caused by the type of this field (text 255)?

Any help would be greatly appreciated!

Thanks,
Thomas

**Comment by CeciAc** [comment]
Hello, @ThomasDebacker 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
