### ISSUE TITLE
access_token and refresh_token can't be decoded by jwt.ms

### ISSUE THREAD

**Issue by omascia** [MicrosoftDocs/azure-docs.fr-fr#307]
I can authorize through the authentication code flow, and then request a token.
Though, while only building the process at this stage, the answer I get presents me with an access_token and a refresh_token which:

1) does not have the three dot separated parts.
2) can't be decoded by https://jwt.ms when pasted over there.

The id_token looks right and can be decoded by jwt.ms, even though I'm surprised the preferred_name is not among the claims.

Are the access_token and refresh_token encoded in a different way than the id_token?
At this point I don't yet know if the access_token will be accepted as is by Microsoft Graph.

Is this all a documentation issue when using v2.0 flows (and I'm right to post here) or is this something which I should obviously discuss elsewhere?

(Those tokens below have been redacted).

{
  "token_type": "Bearer",
  "scope": "openid https://graph.microsoft.com/User.Read",
  "expires_in": 3600,
  "ext_expires_in": 3600,
  "access_token": "EwBoA8l****REDACTED****",
  "refresh_token": "MCei3IBq3dt0tE6cEp****REDACTED***",
  "id_token": "eyJ0****REDACTED***1xbyJ9.eyJ2Z****REDACTED***20.l41KUT5ipc****REDACTED***wow"
}

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ liaison des problèmes GitHub.*

* ID: fef99ca3-72bb-2c48-a62b-9ff9c314d72b
* Version Independent ID: e58fd3a1-0af8-6e16-3d78-3dc748992593
* Content: [Flux de Code OAuth v2.0 d’Azure AD](https://docs.microsoft.com/fr-be/azure/active-directory/develop/v2-oauth2-auth-code-flow#feedback)
* Content Source: [articles/active-directory/develop/v2-oauth2-auth-code-flow.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/active-directory/develop/v2-oauth2-auth-code-flow.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by omascia** [comment]
After some more tests...
In this authentication code flow, "email" is returned within the answer to /authorize if scope "email" has been requested.
The access token and the refresh token are to be taken as opaque and they do work when used. But they can't being decoded by jwt.ms and do not look alike the samples exposed in the doc, which is a bit misleading in this regard. Besides this, it works. :)

**Comment by CeciAc** [comment]
Hello, @omascia 

Your contribution is much appreciated. If you have this kind of issues in the future, please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
