### ISSUE TITLE
Azure Iot Hub - Raspberry Pi - Missing messages

### ISSUE THREAD

**Issue by Durassel** [MicrosoftDocs/azure-docs.fr-fr#308]
I followed this tutorial : https://docs.microsoft.com/fr-fr/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started
I started my Raspberry Pi Node.JS program, sending message each 10 sec.

I have this in my console : 
Sending message: {"messageId":25,"deviceId":"Raspberry Pi Node","temperature":36.00450324861157}
Message sent to Azure IoT Hub
Sending message: {"messageId":26,"deviceId":"Raspberry Pi Node","temperature":40.55359924650331}
Message sent to Azure IoT Hub
Sending message: {"messageId":27,"deviceId":"Raspberry Pi Node","temperature":39.367977865156654}
Message sent to Azure IoT Hub
Sending message: {"messageId":28,"deviceId":"Raspberry Pi Node","temperature":34.62042254725701}
Message sent to Azure IoT Hub
Sending message: {"messageId":29,"deviceId":"Raspberry Pi Node","temperature":38.09156009144509}
Message sent to Azure IoT Hub
Sending message: {"messageId":30,"deviceId":"Raspberry Pi Node","temperature":36.317181831385156}
Message sent to Azure IoT Hub

But, on my Web App, I only received two messages :
receive message{"messageId":25,"deviceId":"Raspberry Pi Node","temperature":36.00450324861157,"time":"2019:04:09T09:18:12"}
receive message{"messageId":30,"deviceId":"Raspberry Pi Node","temperature":36.317181831385156,"time":"2019:04:09T09:19:02"}

Can you help me solve this problem, please ?
Thank you very much,
Fred

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 681e10a1-05d3-5761-2afd-42602a7efecf
* Version Independent ID: f72e21b1-3530-8554-f1f1-fc66b222a485
* Content: [Visualisation en temps réel de données de capteur à partir de votre Azure IoT Hub – Web Apps](https://docs.microsoft.com/fr-fr/azure/iot-hub/iot-hub-live-data-visualization-in-web-apps#feedback)
* Content Source: [articles/iot-hub/iot-hub-live-data-visualization-in-web-apps.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/iot-hub/iot-hub-live-data-visualization-in-web-apps.md)
* Service: **iot-hub**
* GitHub Login: @rangv
* Microsoft Alias: **rangv**

**Comment by CeciAc** [comment]
Hello, @Durassel

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
