### ISSUE TITLE
About guest users and group ownership?

### ISSUE THREAD

**Issue by klem-ent** [MicrosoftDocs/azure-docs.fr-fr#309]
Do a guest user could be set as a group owner?
On my azure portal I can set a guest user as a group owner, but once connected to the protal this guest user is not able to see the group from the groups list.
Is there any other rights or roles that the guest user may have?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 31a86aa3-3274-12eb-66a4-8147c0438ed2
* Version Independent ID: da45ec44-72ee-009c-4c0c-472b496f785c
* Content: [Ajouter ou supprimer les propriétaires d’un groupe – Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners?context=azure%2Factive-directory%2Fusers-groups-roles%2Fcontext%2Fugr-context#feedback)
* Content Source: [articles/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/live/articles/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
Hello, @klem-ent 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
