### ISSUE TITLE
Missing SVG format icons for French-translated sign-in buttons

### ISSUE THREAD

**Issue by pierrepinard-2** [MicrosoftDocs/azure-docs.fr-fr#340]
Hi,

PNG format icons for French-translated sign-in buttons ("Se connecter avec Microsoft" and "Connexion") are available on this page, but there are no SVG format icons.
It's a shame because SVG format gives many advantages over simple PNG format.
Could you please provide the missing icons?

Thank you,
Kind regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 142962d7-66c3-9372-3e3e-c621cba4d881
* Version Independent ID: 748f0246-0a13-e7ed-46dd-be219f19343b
* Content: [Directives de personnalisation des applications](https://docs.microsoft.com/fr-fr/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps#feedback)
* Content Source: [articles/active-directory/develop/howto-add-branding-in-azure-ad-apps.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/develop/howto-add-branding-in-azure-ad-apps.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @CelesteDG
* Microsoft Alias: **celested**

**Comment by pierrepinard-2** [comment]
Hi,

Following my previous comment, I just submitted a Pull Request to the documentation in order to fix the assets (some PNG files were mixed up too).

Kind regards,

**Comment by pierrepinard-2** [comment]
https://github.com/MicrosoftDocs/azure-docs.fr-fr/pull/341

**Comment by CeciAc** [comment]
Hello, @pierrepinard-2
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pierrepinard-2
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/active-directory/develop/howto-add-branding-in-azure-ad-apps

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
