### ISSUE TITLE
Partitioned parquet files

### ISSUE THREAD

**Issue by naceurbensaid** [MicrosoftDocs/azure-docs.fr-fr#380]
Hello,
How can we write partitioned files (not partitioned path) with ADF ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cd297884-8924-9f6b-3ed6-738ef10b27a1
* Version Independent ID: 7bff0c0c-66fe-481c-0e83-0e154c46510e
* Content: [Guide pratique pour lire et écrire des données partitionnées dans Azure Data Factory](https://docs.microsoft.com/fr-fr/azure/data-factory/how-to-read-write-partitioned-data)
* Content Source: [articles/data-factory/how-to-read-write-partitioned-data.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/data-factory/how-to-read-write-partitioned-data.md)
* Service: **data-factory**
* GitHub Login: @sharonlo101
* Microsoft Alias: **shlo**

**Comment by CeciAc** [comment]
Hello, @naceurbensaid 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
