### ISSUE TITLE
Dead Link

### ISSUE THREAD

**Issue by hoshiylia** [MicrosoftDocs/azure-docs.fr-fr#396]
Link for "Registration form" on part 3. is dead 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e16147fb-8da4-6c41-be0f-b2856043c7c9
* Version Independent ID: dab8f3c3-c3ff-883b-406d-405701a53224
* Content: [Devenir éditeur sur les vitrines de la place de marché](https://docs.microsoft.com/fr-fr/azure/marketplace/become-publisher#feedback)
* Content Source: [articles/marketplace/become-publisher.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/marketplace/become-publisher.md)
* Service: **marketplace**
* GitHub Login: @ellacroi
* Microsoft Alias: **ellacroi**

**Comment by CeciAc** [comment]
Hello, @hoshiylia 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
The link the contributor is reporting is not present in the en-US page which was recently updated
Please, check and let us know is there something we can do on our end
kind regards

**Comment by ishasahni1** [comment]
@CeciAc looks like file is in localization status, I am following up with production team on ETA for the file.

**Comment by CeciAc** [comment]
@ishasahni1 @hoshiylia It looks like this issue doesn't repro anymore after the update
please confirm so we can close the ticket

best regards

**Comment by ishasahni1** [comment]
@CeciAc yes I think we can close this issue. As file is now localized.

**Comment by CeciAc** [comment]
Hello, @hoshiylia

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/marketplace/become-publisher

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
