### ISSUE TITLE
Microsoft peering max prefix length

### ISSUE THREAD

**Issue by fdebonneval** [MicrosoftDocs/azure-docs.fr-fr#403]
Hi,

I'd like to know what are the max v4 and v6 max prefix length on the Microsoft Peering ? /24 and /48 ?
Would be great to add the information in this section of the documentation,

Thx,
FB

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b29b475d-056b-ba43-5309-dd1ee50b4318
* Version Independent ID: 55d5f203-32ef-40a1-62fa-83e8c81cdb14
* Content: [Configuration requise - ExpressRoute : Azure](https://docs.microsoft.com/fr-fr/azure/expressroute/expressroute-routing)
* Content Source: [articles/expressroute/expressroute-routing.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/expressroute/expressroute-routing.md)
* Service: **expressroute**
* GitHub Login: @ganesr
* Microsoft Alias: **ganesr**

**Comment by CeciAc** [comment]
Hello, @fdebonneval

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
