### ISSUE TITLE
Informations sur le fonctionnement du conteneur

### ISSUE THREAD

**Issue by MrVhek** [MicrosoftDocs/azure-docs.fr-fr#444]
Bonjour,
J'aimerais avoir plus d'informations sur la manière dont fonctionne le service qui gère les conteneurs. J'ai une application Django déployée sur une Webapp Linux Docker avec un serveur de socket UWSGI.
Quand je la déploie sur Azure, elle est accessible sur https://monapp.azurewebsites.net, je me pose donc la question de savoir s'il y a un serveur web qui la gère après mon conteneur pour automatiquement mettre le https et rediriger mon app du port 8000 aux ports 80/463 ?
Je vois beaucoup de tutoriels utiliser un Web Server dans le Docker, le faut t'il obligatoirement ? Ou peux on avoir accès au serveur web qui a l'air de rediriger mon application pour lui passer des paramètres additionnels (comme la compression GZIP par exemple) ?
Merci d'avance de vos réponses !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6489b871-9cf8-7c99-9834-076ec646d0e6
* Version Independent ID: fa5d2995-5833-c04b-2530-c100bcd1e76b
* Content: [Configurer le conteneur personnalisé - Azure App Service](https://docs.microsoft.com/fr-fr/azure/app-service/containers/configure-custom-container#feedback)
* Content Source: [articles/app-service/containers/configure-custom-container.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/containers/configure-custom-container.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by CeciAc** [comment]
Bonjour @MrVhek 

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
