### ISSUE TITLE
Vous avez remplacé "Français" par "Anglais" avant "fr"

### ISSUE THREAD

**Issue by dechiktorren** [MicrosoftDocs/azure-docs.fr-fr#464]
c'est un peut vexant que même :p

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 62643b2a-6080-150d-7e04-11b0250f22dc
* Version Independent ID: e7ffbecc-52e6-f356-e3d6-d3392711921c
* Content: [Prise en charge linguistique - API Analyse de texte - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/text-analytics/language-support)
* Content Source: [articles/cognitive-services/text-analytics/language-support.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/text-analytics/language-support.md)
* Service: **cognitive-services**
* Sub-service: **text-analytics**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by CeciAc** [comment]
Bonjour, @dechiktorren 

Merci pour votre feedback. 

Nous révisons activement vos commentaires et nous vous recontacterons bientôt. 

Cordialement, 
L’équipe Microsoft DOCS International

**Comment by CeciAc** [comment]
@ishasahni1 the last version of this file is in "on-hold" status and will likely be delivery on July.

**Comment by CeciAc** [comment]
Bonjour @dechiktorren

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/cognitive-services/text-analytics/language-support du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
