### ISSUE TITLE
Question : Comment gérer le flux de mises à jour du contenu anglais ?

### ISSUE THREAD

**Issue by SphinxKnight** [MicrosoftDocs/azure-docs.fr-fr#469]
Quels sont les outils utilisés pour identifier le contenu français qui a besoin d'être mis à jour par rapport au contenu anglais?
Autrement dit : comment synchroniser efficacement les modifications en-US sur fr-fr ?

Merci d'avance pour votre réponse :)

**Comment by SphinxKnight** [comment]
Contexte : la réponse m'intéresse en tant potentiel contributeur à ces traductions et en tant que traducteur sur MDN où du contenu pourrait être stocké sur GitHub.

**Comment by CeciAc** [comment]
Hi @ishasahni1 
can you please check this issue?

**Comment by SphinxKnight** [comment]
If this needs rephrasing in English, my question is 'how do you ensure the fr-fr content does not "get stale" vs. the en-US content esp. when storing the content under a GH repo?'. Is there any open tool or process that you use for that?

Thanks a lot in advance for the answer :) (even if it is "there is no tool / process, only best effort)

**Comment by ishasahni1** [comment]
@SphinxKnight thank you so much for rephrasing content in English. We do localization for content every week. Having been said if there is any topic say in en-us updated on 6/24 today, it will be picked up for localization on Azure every Wednesday in this case say 6/26 and will be pack in 5-7 BD. So in an ideal scenario loc is behind en-us by a week.

Please let us know if this information helps.

**Comment by SphinxKnight** [comment]
@ishasahni1 Thanks a lot for the answers. Do you have a specific tool (with UI and such) to gather all of the updated content or is this something like a script?

Last but not least, all of the translation efforts rely on employees/contractor efforts or is this more driven by community/volunteer?

Thanks!

**Comment by ishasahni1** [comment]
@SphinxKnight Yes all the new updates in the en-us repo are automatically picked up from our automation pipeline and pushed out for localization. All our content is localized through our loc supplier but we also welcome community contribution on our content. 

The contribution is reviewed by our supplier team and if they agree to the contribution is accepted and reflects live on our localized content.

**Comment by SphinxKnight** [comment]
Thanks a lot!
