### ISSUE TITLE
Import Problem

### ISSUE THREAD

**Issue by ddoussot** [MicrosoftDocs/azure-docs.fr-fr#476]
This line does not work for me :
import android.support.v4.app.NotificationCompat;

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: affa806e-ed31-20b7-9aee-2b56572225ab
* Version Independent ID: 5dea14a7-065e-c21b-712c-0cee7d3ffb16
* Content: [Notifications Push vers des applications Android avec Azure Notification Hubs et Firebase Cloud Messaging](https://docs.microsoft.com/fr-fr/azure/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started#feedback)
* Content Source: [articles/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/notification-hubs/notification-hubs-android-push-notification-google-fcm-get-started.md)
* Service: **notification-hubs**
* GitHub Login: @jwargo
* Microsoft Alias: **jowargo**

**Comment by ddoussot** [comment]
Finally worked by replacing by this line :
    implementation 'androidx.legacy:legacy-support-v13:1.0.0'

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #34044](https://github.com/MicrosoftDocs/azure-docs/issues/34044) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ddoussot

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by ddoussot** [comment]
Hello

Waouh ! Thank u for being so reactive :-)

Cheers

Le 26 juin 2019 19:11, Cecilia Acevedo <notifications@github.com> a écrit :

Hello, @ddoussot<https://github.com/ddoussot>

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - XXX.

We truly appreciate your contribution to our articles.

Kind regards,
Microsoft DOCS International Team
