### ISSUE TITLE
One key per VM ?

### ISSUE THREAD

**Issue by wouli-29** [MicrosoftDocs/azure-docs.fr-fr#487]
Hello
I need to understand and could not find an explanation anywhere.
I have a bunch of VMs where I need to encrypt disks.
Should I create one key in the key vault per VM or can I use the same key for all the VMs ?
Thank you

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 86b44bac-c760-a06d-e618-149f275e0d0e
* Version Independent ID: bcaaf53e-87c1-59aa-c51b-d3359ebb9046
* Content: [Chiffrer des disques sur une machine virtuelle Windows dans Azure](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/encrypt-disks#feedback)
* Content Source: [articles/virtual-machines/windows/encrypt-disks.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/virtual-machines/windows/encrypt-disks.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by CeciAc** [comment]
Hello, @wouli-29

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
