### ISSUE TITLE
PB PDO PHP

### ISSUE THREAD

**Issue by miguelcogiway** [MicrosoftDocs/azure-docs.fr-fr#494]
$options = array(
    PDO::MYSQL_ATTR_SSL_CA =&gt; '/var/www/html/BaltimoreCyberTrustRoot.crt.pem'
);
$db = new PDO('mysql:host=mydemoserver.mysql.database.azure.com;port=3306;dbname=databasename', 'username@mydemoserver', 'yourpassword', $options);

==&gt; ça n'a pas marché pour moi

Par contre : 

$options = array(
    PDO::MYSQL_ATTR_INIT_COMMAND =&gt; 'SET NAMES utf8',
    PDO::MYSQL_ATTR_SSL_CA =&gt; '/var/www/html/BaltimoreCyberTrustRoot.crt.pem',
    PDO::MYSQL_ATTR_SSL_VERIFY_SERVER_CERT =&gt; false,
);
$db = new PDO('mysql:host=mydemoserver.mysql.database.azure.com;port=3306;dbname=databasename', 'username@mydemoserver', 'yourpassword', $options);

==&gt; là ça marche

Mes sources : https://www.saotn.org/how-to-use-ssl-in-php-data-objects-pdo-mysql/

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 77a94e6f-a799-494f-f2f9-171c1804e5f4
* Version Independent ID: 0ca5e2ae-5889-61ef-3ce7-5c447f7519a6
* Content: [Configurer la connectivité SSL pour se connecter en toute sécurité à Azure Database pour MySQL](https://docs.microsoft.com/fr-fr/azure/mysql/howto-configure-ssl#feedback)
* Content Source: [articles/mysql/howto-configure-ssl.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/mysql/howto-configure-ssl.md)
* Service: **mysql**
* GitHub Login: @ajlam
* Microsoft Alias: **andrela**

**Comment by CeciAc** [comment]
Bonjour @miguelcogiway  

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
