### ISSUE TITLE
Backend pools number when autoscaling

### ISSUE THREAD

**Issue by rabbboudi** [MicrosoftDocs/azure-docs.fr-fr#511]
[Tapez vos commentaires ici]
Does the auto-scaling remove the limit related to the backend pools number (limited to 100) ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: faa5b8a2-11a1-6a2d-07cb-ffcf39643ed4
* Version Independent ID: 298a134e-fb27-f16d-bff2-d43eb0f766fd
* Content: [Mise à l’échelle et la passerelle d’Application redondant dans Azure](https://docs.microsoft.com/fr-fr/azure/application-gateway/application-gateway-autoscaling-zone-redundant)
* Content Source: [articles/application-gateway/application-gateway-autoscaling-zone-redundant.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/application-gateway/application-gateway-autoscaling-zone-redundant.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by lichasu** [comment]
Hello, @rabbboudi ,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
