### ISSUE TITLE
Example of PowerShell Script needs to be updated to be compatible with ASDK version

### ISSUE THREAD

**Issue by dtizon** [MicrosoftDocs/azure-docs.fr-fr#52]
Please replace: 
Add-AzureStackAzureRmEnvironment --> Add-AzureRMEnvironment
Get-DirectoryTenantID  --> Get-AzsDirectoryTenantId

**Comment by SnehaGunda** [comment]
@dtizon thanks for pointing, I have updated the doc, the changes should be live later today.

**Comment by SunnyDeng** [comment]
French version released as well.
