### ISSUE TITLE
Transaltion issue with "free" ?

### ISSUE THREAD

**Issue by blogh** [MicrosoftDocs/azure-docs.fr-fr#522]
"Alternatively, if you have provisioned 10 GB of storage, the storage size is increase to 15 GB when less than 1 GB of storage is free."

was transalated to the followin in french :

"Vous pouvez également, si vous avez approvisionné 10 Go de stockage, la taille de stockage est augmentation à 15 Go lorsque moins de 1 Go de stockage est gratuit."

The sentence is hard to understand in french plus "gratuit" means free of charge. From what I understand of the english sentence it's not what was intended. was it ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 038ee2b6-8a76-a678-1069-3eb7c2808d73
* Version Independent ID: cd6cb2ea-9fff-9237-2168-a39eb24f2677
* Content: [Niveaux tarifaires pour Azure Database pour PostgreSQL - serveur unique](https://docs.microsoft.com/fr-fr/azure/postgresql/concepts-pricing-tiers#feedback)
* Content Source: [articles/postgresql/concepts-pricing-tiers.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/postgresql/concepts-pricing-tiers.md)
* Service: **postgresql**
* GitHub Login: @jan-eng
* Microsoft Alias: **janeng**

**Comment by lichasu** [comment]
Hello, @blogh , 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @blogh 

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/postgresql/concepts-pricing-tiers du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
