### ISSUE TITLE
Azure VM recommended size

### ISSUE THREAD

**Issue by rabbboudi** [MicrosoftDocs/azure-docs.fr-fr#560]
[Tapez vos commentaires ici]
Does Azure Advisor give sizing recommendations based on the VM's metrics as it is the case in Cloudyn reports ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: b703202c-7c7d-7177-6496-d1c61dacf22b
* Version Independent ID: f9ee0bcc-f74a-dbba-c9b9-f84bf7b800a7
* Content: [Réduire les coûts de service grâce à Azure Advisor](https://docs.microsoft.com/fr-fr/azure/advisor/advisor-cost-recommendations#optimize-virtual-machine-spend-by-resizing-or-shutting-down-underutilized-instances)
* Content Source: [articles/advisor/advisor-cost-recommendations.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/advisor/advisor-cost-recommendations.md)
* Service: **advisor**
* GitHub Login: @kasparks
* Microsoft Alias: **kasparks**

**Comment by srvbpigh** [comment]
Hello, @rabbboudi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @rabbboudi

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
