### ISSUE TITLE
Is password writeback compatible with password filter ?

### ISSUE THREAD

**Issue by kayasax** [MicrosoftDocs/azure-docs.fr-fr#564]
Hi please specify if password filters (https://docs.microsoft.com/en-us/windows/win32/secmgmt/password-filters) are supported in this scenario.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ebc51bb0-dd9d-cb3f-3e3f-b9765b48f21d
* Version Independent ID: d597a70e-8fb1-0e4e-8ae0-e3cd87de1118
* Content: [Intégration de la réécriture du mot de passe locale avec la réinitialisation de mot de passe en libre-service Azure AD - Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/authentication/concept-sspr-writeback)
* Content Source: [articles/active-directory/authentication/concept-sspr-writeback.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/authentication/concept-sspr-writeback.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @kayasax
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by MicrosoftGuyJFlo** [comment]
Yes password filters are supported. The password is written to on-premises AD first and once approved as meeting the complexity requirements on-premises is then written to Azure AD.

**Comment by CeciAc** [comment]
Hello, @kayasax

Your contribution is much appreciated. 
Please rember you can log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
