### ISSUE TITLE
HybridWorker Group created by this script

### ISSUE THREAD

**Issue by pajcarpentier** [MicrosoftDocs/azure-docs.fr-fr#606]
Hello all.

you should precise that the Hyrid Worker group is created by the script New-OnPremiseHybridWorker.ps1.
As it is a mandatory field, and there is nowhere it is explain that the Hybrid worker group is created when installing the Hybrid Worker, it makes confusion on the field.
Thank you.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7b29372c-7bd9-7da2-4cff-9afbb432bccf
* Version Independent ID: 66ce101d-d21b-3fdf-be70-7f9cadc1570e
* Content: [Runbook Worker hybride Windows Azure Automation](https://docs.microsoft.com/fr-fr/azure/automation/automation-windows-hrw-install#feedback)
* Content Source: [articles/automation/automation-windows-hrw-install.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/automation/automation-windows-hrw-install.md)
* Service: **automation**
* Sub-service: **process-automation**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by srvbpigh** [comment]
Hello, @pajcarpentier
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pajcarpentier

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue #607 
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
