### ISSUE TITLE
HybridWorker Group created by this script

### ISSUE THREAD

**Issue by pajcarpentier** [MicrosoftDocs/azure-docs.fr-fr#607]
Hello all.

you should precise that the Hyrid Worker group is created by the script New-OnPremiseHybridWorker.ps1.
As it is a mandatory field, and there is nowhere it is explain that the Hybrid worker group is created when installing the Hybrid Worker, it makes confusion on the field.

I mean, the following section :

"When the agent has successfully connected to Azure Monitor logs, it's listed on the Connected Sources tab of the log analytics Settings page. You can verify that the agent has correctly downloaded the Automation solution when it has a folder called AzureAutomationFiles in C:\Program Files\Microsoft Monitoring Agent\Agent. To confirm the version of the Hybrid Runbook Worker, you can browse to C:\Program Files\Microsoft Monitoring Agent\Agent\AzureAutomation\ and note the \version subfolder."
 
has to be updated as the subfolder "AzureAutomationFiles" is only installed after the "New-OnPremiseHybridWorker.ps1" script has been ran on the On Premise machine.

Thank you.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7b29372c-7bd9-7da2-4cff-9afbb432bccf
* Version Independent ID: 66ce101d-d21b-3fdf-be70-7f9cadc1570e
* Content: [Runbook Worker hybride Windows Azure Automation](https://docs.microsoft.com/fr-fr/azure/automation/automation-windows-hrw-install#feedback)
* Content Source: [articles/automation/automation-windows-hrw-install.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/automation/automation-windows-hrw-install.md)
* Service: **automation**
* Sub-service: **process-automation**
* GitHub Login: @bobbytreed
* Microsoft Alias: **robreed**

**Comment by srvbpigh** [comment]
Hello, @pajcarpentier
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @pajcarpentier

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://docs.microsoft.com/fr-fr/azure/automation/automation-windows-hrw-install#feedback

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
