### ISSUE TITLE
Certificates

### ISSUE THREAD

**Issue by LeoGoGarcia** [MicrosoftDocs/azure-docs.fr-fr#610]
Hello, 

2 points to be still explicit in the article: 

1) how to load CERTIFICATES with the key vault reference. Today searching for the information I found that the the certificate is under the SECRET path and not CERTIFICATE. Example: @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mycertificate/ec96f02080254f109c51a1f14cdb1931) instead of @Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/certificate/mycertificate/ec96f02080254f109c51a1f14cdb1931)

2) When developing we'll use our local config file with a string for a secret. Under production environment this secret string will be replaced by the key vault reference. How exactly this works for certificates? In other words: how to do a local development reference of a secret in the application configuration? 

Thanks in advance,

Leo

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7feaa3d0-7233-a3cb-cb9b-a9a55b1f0d7a
* Version Independent ID: f41f9d51-52f8-1f45-1043-1344a3b74458
* Content: [Informations de référence sur Key Vault – Azure App Service](https://docs.microsoft.com/fr-fr/azure/app-service/app-service-key-vault-references)
* Content Source: [articles/app-service/app-service-key-vault-references.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/app-service-key-vault-references.md)
* Service: **app-service**
* GitHub Login: @mattchenderson
* Microsoft Alias: **mahender**

**Comment by srvbpigh** [comment]
Hello, @LeoGoGarcia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LeoGoGarcia

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
