### ISSUE TITLE
forceTakeover

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/azure-docs.fr-fr#625]
Confirm-MsolDomain -DomainName ... -ForceTakeover Force

Confirm-MsolDomain : Unable to verify this domain because it is used elsewhere in Office 365. Remove the verified
domain from the other service before adding it here.

il fut un temps ou il y avait une procédure pour récupéré un compte admin mais elle semble avoire disparue pour ne pas etre remplacer !

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: cd934d58-08f8-a3ca-2686-0006b0b8f74a
* Version Independent ID: 84d9cab3-09b7-95ba-83ea-435ca0ccbb47
* Content: [Prise de contrôle administrateur d’un annuaire non géré Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/users-groups-roles/domains-admin-takeover#feedback)
* Content Source: [articles/active-directory/users-groups-roles/domains-admin-takeover.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/users-groups-roles/domains-admin-takeover.md)
* Service: **active-directory**
* Sub-service: **users-groups-roles**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @CallMeByMyName
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @CallMeByMyName

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
