### ISSUE TITLE
Code illisible, text <span data-ttu-id="6da08-156"> a supprimer

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/azure-docs.fr-fr#633]
Dans les zones d'exemple, il y a des "&lt;span data-ttu-id="6da08-156"&gt;" et autre code HTML qui empêchent la lecture.
Merci de corriger l'affichage.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9eb97eff-d72e-ffa6-1365-5419e93ed82a
* Version Independent ID: 5c8b677b-f4cd-0bb5-c7d6-9b1ef903dad4
* Content: [Azure AD Connect : Authentification unique transparente - Questions fréquentes](https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/how-to-connect-sso-faq#feedback)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sso-faq.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/hybrid/how-to-connect-sso-faq.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by CeciAc** [comment]
Bonjour @GowaP

Merci pour votre feedback. 

Notre équipe d’ingénieurs a révisé vos suggestions et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/how-to-connect-sso-faq#feedback du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
