### ISSUE TITLE
automatiser "substituer la clé de déchiffrement Kerberos" via AAD

### ISSUE THREAD

**Issue by GowaP** [MicrosoftDocs/azure-docs.fr-fr#634]
Microsoft conseil de substituer la clé tous les 30 jours : vu la fréquence, ce traitement devrait être automatique et transparent. il n'y a aucune raison de demande une action manuel lorsque cela devient régulier. Merci d'améliorer le programme AAD pour qu'il procède automatiquement et sans intervention humaine cette substitution.
La saisie de code PowerShell doit rester l'usage pour des besoins de configuration et d'administration ; là, on est dans un besoin régulier. aucune raison de rester manuel ni même d'être obligatoirement fait en PowerShell. Au minimum, merci d'ajouter un bouton dans AAD pour effectuer ce traitement.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9eb97eff-d72e-ffa6-1365-5419e93ed82a
* Version Independent ID: 5c8b677b-f4cd-0bb5-c7d6-9b1ef903dad4
* Content: [Azure AD Connect : Authentification unique transparente - Questions fréquentes](https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/how-to-connect-sso-faq#feedback)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sso-faq.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/hybrid/how-to-connect-sso-faq.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @GowaP
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @GowaP

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation. 

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs. 

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal. 

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
