### ISSUE TITLE
Alertes sur un job en erreur

### ISSUE THREAD

**Issue by GuiRoux5555** [MicrosoftDocs/azure-docs.fr-fr#635]
Bonjour, il n'est apparemment pas possible de créer une alerte sur un job qui tomberait en erreur.
Il y a t'il une solution alternative?

Merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6767b9dc-e2bf-8ee2-ae96-660a948e1f43
* Version Independent ID: 72805516-f205-b2ec-85c9-977ee9bc3f5b
* Content: [Surveiller des travaux dans Azure Data Lake Analytics avec le portail Azure](https://docs.microsoft.com/fr-fr/azure/data-lake-analytics/data-lake-analytics-monitor-and-troubleshoot-jobs-tutorial#feedback)
* Content Source: [articles/data-lake-analytics/data-lake-analytics-monitor-and-troubleshoot-jobs-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/data-lake-analytics/data-lake-analytics-monitor-and-troubleshoot-jobs-tutorial.md)
* Service: **data-lake-analytics**
* GitHub Login: @saveenr
* Microsoft Alias: **saveenr**

**Comment by srvbpigh** [comment]
Hello, @GuiRoux5555
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Bonjour @GuiRoux5555 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton « Envoyer des commentaires sur le produit » qui se trouve au bas de la page DOCS.

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal.

Nous apprécions réellement votre contribution à nos articles.

L’équipe internationale de Microsoft DOCS
