### ISSUE TITLE
Commande inutile

### ISSUE THREAD

**Issue by ealcyon** [MicrosoftDocs/azure-docs.fr-fr#636]
Bonjour,
A quoi sert la commande "export AZURE_STORAGE_CONNECTION_STRING" ?
Merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 619ea303-7632-eaf6-c106-838ee2efec8e
* Version Independent ID: 7b0cdc68-58d4-90f3-11e9-c7bf9afb59a1
* Content: [Restaurer un disque de machine virtuelle avec Sauvegarde Azure](https://docs.microsoft.com/fr-fr/azure/backup/tutorial-restore-disk?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json#convert-the-restored-disk-to-a-managed-disk)
* Content Source: [articles/backup/tutorial-restore-disk.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/backup/tutorial-restore-disk.md)
* Service: **backup**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by srvbpigh** [comment]
Hello, @ealcyon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Bonjour @ealcyon 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton « Envoyer des commentaires sur le produit » qui se trouve au bas de la page DOCS.

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal.

Nous apprécions réellement votre contribution à nos articles.

L’équipe internationale de Microsoft DOCS
