### ISSUE TITLE
Yammer app

### ISSUE THREAD

**Issue by jeffangama** [MicrosoftDocs/azure-docs.fr-fr#639]
DOes yammer app get the SSO once this is configured ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2010f5ac-1080-addd-1fb3-5b05db26c1f6
* Version Independent ID: 1aa18d6a-5846-7989-b844-fc8ad027921b
* Content: [Azure AD Connect : Authentification unique transparente](https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/how-to-connect-sso)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sso.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/hybrid/how-to-connect-sso.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @jeffangama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @jeffangama

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
