### ISSUE TITLE
Lien vers les commandes 

### ISSUE THREAD

**Issue by michel-priori** [MicrosoftDocs/azure-docs.fr-fr#641]
merci d'ajouter les liens vers les commandes qui permettent effectivement de mettre cette fonctionnalité en oeuvre.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a825ecf0-9d63-29be-8e8a-aab285a53c7a
* Version Independent ID: 4e25d0f7-56b5-3229-89d8-7509264647a5
* Content: [Récupération accélérée de base de données - Azure SQL Database](https://docs.microsoft.com/fr-fr/azure/sql-database/sql-database-accelerated-database-recovery#feedback)
* Content Source: [articles/sql-database/sql-database-accelerated-database-recovery.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/sql-database/sql-database-accelerated-database-recovery.md)
* Service: **sql-database**
* Sub-service: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @michel-priori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @michel-priori 

Merci pour votre feedback. Nous sommes heureux d’apprendre que notre documentation répond à vos attentes. 
Dans une optique d’amélioration constante, nous vous encourageons à envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
