### ISSUE TITLE
Recommandations et limites

### ISSUE THREAD

**Issue by michel-priori** [MicrosoftDocs/azure-docs.fr-fr#642]
la préconisation est de mettre le fichier LDF sur un autre disque que les fichiers de données. 
Qu'en est-il pour le fichier sLOG ? avec le fichier de LOG ? avec les données ? ailleurs ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a825ecf0-9d63-29be-8e8a-aab285a53c7a
* Version Independent ID: 4e25d0f7-56b5-3229-89d8-7509264647a5
* Content: [Récupération accélérée de base de données - Azure SQL Database](https://docs.microsoft.com/fr-fr/azure/sql-database/sql-database-accelerated-database-recovery#feedback)
* Content Source: [articles/sql-database/sql-database-accelerated-database-recovery.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/sql-database/sql-database-accelerated-database-recovery.md)
* Service: **sql-database**
* Sub-service: **high-availability**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @michel-priori
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @michel-priori 

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/41450

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
