### ISSUE TITLE
Retrieving Hotmail/Live (Consumer Microsoft Account) profile Photo once signed in through Azure AD B2C

### ISSUE THREAD

**Issue by LaurentTermeau** [MicrosoftDocs/azure-docs.fr-fr#650]
Hello, 
I'm creating an ASP.NET Core MVC App. I'm using Azure AD B2C to allow users to sign in through several Identity providers (Google, Facebook, Microsoft Account ). 
Signin process works just fine. I'm able tio use the Access Token return in Claims to access Facebook User Profile Photo, but I can't do the same for a Microsoft Account. 
It seems that the Microsoft Graph API does not allow access to User's profile Photo. 

What is the recommended way to retrieve a Consumer Microsoft Account  User's Photo after sign in ? 
- Graph.microsoft.com ?  
- Graph.windows.net ?  
- Windows Live API ? 
Thanks, 
Laurent. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4a4b8453-d2bc-9c8d-bb16-26fa7e4c6363
* Version Independent ID: 160642fc-b5a9-1ebe-7daf-105509b6e2f4
* Content: [Utiliser l’API Graph dans Azure Active Directory B2C](https://docs.microsoft.com/fr-fr/azure/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory-b2c/active-directory-b2c-devquickstarts-graph-dotnet.md)
* Service: **active-directory**
* Sub-service: **b2c**
* GitHub Login: @mmacy
* Microsoft Alias: **marsma**

**Comment by srvbpigh** [comment]
Hello, @LaurentTermeau
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @LaurentTermeau 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41710

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
