### ISSUE TITLE
Unable to disable 2FA

### ISSUE THREAD

**Issue by bc-109** [MicrosoftDocs/azure-docs.fr-fr#651]
2FA is disabled at organization level.
2FA is disabled individually for each user.
But when I log in, the system still continues to ask for 2FA. This breaks a third-party app, which does not recognize 2FA.
--
Is this article wrong, or is the 2FA mechanism wrong ?
--
The expected behavior would be to be able to enable / disable 2FA for every user. But as this does not seem to work at all, please provide a (working) way to disable 2FA completely.

Kind regards

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 276c38fe-aa72-6afa-23d8-14ff206c6f50
* Version Independent ID: 9ffe59dd-c667-4802-1da0-6917638804c5
* Content: [Résoudre les problèmes courants de vérification à deux facteurs - Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot)
* Content Source: [articles/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/user-help/multi-factor-authentication-end-user-troubleshoot.md)
* Service: **active-directory**
* Sub-service: **user-help**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by srvbpigh** [comment]
Hello, @bc-109
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #42064](https://github.com/MicrosoftDocs/azure-docs/issues/42064) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @bc-109 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/42064

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
