### ISSUE TITLE
Petite faute d'ortho

### ISSUE THREAD

**Issue by eti3007** [MicrosoftDocs/azure-docs.fr-fr#655]
Dans le sous chapitre  "Prise en charge régionale" la deuxième phrase devrait commencer par :

Toutes les régions

Merci

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0d150ace-bd6d-8111-79b5-0ce7cb76a378
* Version Independent ID: 13a828ae-ae92-9ea7-5f37-5a69eeeb87b7
* Content: [Azure Shared Image Gallery](https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/shared-image-galleries#feedback)
* Content Source: [articles/virtual-machines/windows/shared-image-galleries.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/virtual-machines/windows/shared-image-galleries.md)
* Service: **virtual-machines-windows**
* GitHub Login: @axayjo
* Microsoft Alias: **akjosh**

**Comment by srvbpigh** [comment]
Hello, @eti3007
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @eti3007

Merci pour votre feedback. 

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/virtual-machines/windows/shared-image-galleries#feedback du site Docs.  

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft. 

Cordialement, 
L’équipe Microsoft DOCS International
