### ISSUE TITLE
Erreur à l'inscription de l'application

### ISSUE THREAD

**Issue by Nathure** [MicrosoftDocs/azure-docs.fr-fr#659]
Il faut absolument une adresse en https pour pouvoir enregistrer une url de redirection.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 4c6d2219-cb28-5527-1079-6e3195cad282
* Version Independent ID: 70c2aad0-6883-51a9-fed7-01be62302483
* Content: [Configuration guidée d’une application monopage (SPA) JavaScript Azure AD v2.0 - Microsoft identity platform](https://docs.microsoft.com/fr-fr/azure/active-directory/develop/tutorial-v2-javascript-spa#feedback)
* Content Source: [articles/active-directory/develop/tutorial-v2-javascript-spa.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/develop/tutorial-v2-javascript-spa.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @navyasric
* Microsoft Alias: **nacanuma**

**Comment by srvbpigh** [comment]
Hello, @Nathure
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour, @Nathure
Nous vous remercions sincèrement pour votre commentaire et nous nous efforçons d’améliorer votre expérience dans docs.microsoft.com. Cependant, nous avons besoin de plus d’informations pour pouvoir répondre à vos commentaires. Pouvez-vous fournir des informations plus détaillées et clarifier votre commentaire ?

Cordialement,
L’équipe internationale Microsoft DOCS

**Comment by CeciAc** [comment]
Bonjour, @Nathure

Nous revenons vers vous au sujet de notre précédent commentaire. Nous avons besoin de plus d’informations pour pouvoir répondre à vos commentaires. Pouvez-vous fournir des informations plus détaillées et clarifier votre commentaire ?

Cordialement,
L’équipe internationale Microsoft DOCS

**Comment by Nathure** [comment]
Bonjour,
Pour pouvoir enregistrer une application dans AzureAD, l'url de redirection doit être en https.
Votre exemple parle d'adresse en http, on ne peut pas utiliser l'authentification OAuth sans https.
Cordialement,

**Comment by CeciAc** [comment]
Bonjour @Nathure

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise. 

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/44300

Votre contribution à nos articles est grandement appréciée.  

Cordialement, 
L’équipe Microsoft DOCS International
