### ISSUE TITLE
MACOs IKEv2 and certificate

### ISSUE THREAD

**Issue by sushiMix** [MicrosoftDocs/azure-docs.fr-fr#661]
[Tapez vos commentaires ici]
For macOS Catalina, you need to specify none for the authentication and the certificate in the sub menu. Selecting certificate as described in the documentation will fail.

https://discussions.apple.com/thread/250718975

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 0d5150fc-9936-07cf-dce7-44d0ec114cd0
* Version Independent ID: 8b627174-56cd-a81e-a687-34ba66d33550
* Content: [Créer et installer des fichiers config de client VPN P2S pour l’authentification par certificat Azure : Azure](https://docs.microsoft.com/fr-fr/azure/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert#installmac)
* Content Source: [articles/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/vpn-gateway/point-to-site-vpn-client-configuration-azure-cert.md)
* Service: **vpn-gateway**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by srvbpigh** [comment]
Hello, @sushiMix
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @sushiMix 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/41069
For this reason, we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
