### ISSUE TITLE
upgrade the info with the global reader role for storage account ?

### ISSUE THREAD

**Issue by ehsf973** [MicrosoftDocs/azure-docs.fr-fr#664]
upgrade the info with the global reader role for storage account ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 732eb4b2-7efe-02a0-b905-fe03f9c94e84
* Version Independent ID: 64b0f82c-2d46-92c5-37f7-5e06596171b9
* Content: [Guide de sécurité Azure Storage](https://docs.microsoft.com/fr-fr/azure/storage/common/storage-security-guide)
* Content Source: [articles/storage/common/storage-security-guide.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/storage/common/storage-security-guide.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by srvbpigh** [comment]
Hello, @ehsf973
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ehsf973

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ehsf973 
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
