### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/azure-docs.fr-fr#665]
Powershell version

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 31a86aa3-3274-12eb-66a4-8147c0438ed2
* Version Independent ID: da45ec44-72ee-009c-4c0c-472b496f785c
* Content: [Ajouter ou supprimer les propriétaires d’un groupe – Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners)
* Content Source: [articles/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/fundamentals/active-directory-accessmanagement-managing-group-owners.md)
* Service: **active-directory**
* Sub-service: **fundamentals**
* GitHub Login: @msaburnley
* Microsoft Alias: **ajburnle**

**Comment by srvbpigh** [comment]
Hello, @CallMeByMyName
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @CallMeByMyName 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @CallMeByMyName
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
