### ISSUE TITLE
Python 3 - Feel free to use

### ISSUE THREAD

**Issue by JamesDLD** [MicrosoftDocs/azure-docs.fr-fr#666]
Hello,
as you probably know Python 2 End of Life has been announced as January 1st 2020.
I did add below a sample code for Python 3.

'''
import json
import requests
import datetime
import hashlib
import hmac
import base64

# Replace with your Workspace ID
customer_id = "xxxxxxxx"

# Replace with your Primary Key
shared_key = "xxxxxxxx"

# The log type is the name of the event that is being submitted
log_type = 'WebMonitorTest'

# An example JSON web monitor object
json_data = [{
    "slot_ID": 12345,
    "ID": "5cdad72f-c848-4df0-8aaa-ffe033e75d57",
    "availability_Value": 100,
    "performance_Value": 6.954,
    "measurement_Name": "last_one_hour",
    "duration": 3600,
    "warning_Threshold": 0,
    "critical_Threshold": 0,
    "IsActive": "true"
},
    {
    "slot_ID": 67890,
    "ID": "b6bee458-fb65-492e-996d-61c4d7fbb942",
    "availability_Value": 100,
    "performance_Value": 3.379,
    "measurement_Name": "last_one_hour",
    "duration": 3600,
    "warning_Threshold": 0,
    "critical_Threshold": 0,
    "IsActive": "false"
}]
body = json.dumps(json_data)

#####################
######Functions######
#####################

# Build the API signature

def build_signature(customer_id, shared_key, date, content_length, method, content_type, resource):
    x_headers = 'x-ms-date:' + date
    string_to_hash = method + "\n" + \
        str(content_length) + "\n" + content_type + \
        "\n" + x_headers + "\n" + resource
    bytes_to_hash = str.encode(string_to_hash, 'utf-8')
    decoded_key = base64.b64decode(shared_key)
    encoded_hash = (base64.b64encode(hmac.new(
        decoded_key, bytes_to_hash, digestmod=hashlib.sha256).digest())).decode()
    authorization = "SharedKey {}:{}".format(customer_id, encoded_hash)
    return authorization

# Build and send a request to the POST API

def post_data(customer_id, shared_key, body, log_type):
    method = 'POST'
    content_type = 'application/json'
    resource = '/api/logs'
    rfc1123date = datetime.datetime.utcnow().strftime('%a, %d %b %Y %H:%M:%S GMT')
    content_length = len(body)
    signature = build_signature(
        customer_id, shared_key, rfc1123date, content_length, method, content_type, resource)
    uri = 'https://' + customer_id + '.ods.opinsights.azure.com' + \
        resource + '?api-version=2016-04-01'

    headers = {
        'content-type': content_type,
        'Authorization': signature,
        'Log-Type': log_type,
        'x-ms-date': rfc1123date
    }

    response = requests.post(uri, data=body, headers=headers)
    if (response.status_code &gt;= 200 and response.status_code &lt;= 299):
        print('Accepted')
    else:
        print("Response code: {}".format(response.status_code))

post_data(customer_id, shared_key, body, log_type)

'''

James

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 1295e1b3-5aed-3aee-4331-8b81e7a7e544
* Version Independent ID: 3c00a5ee-7093-1e8b-9004-8fed3f82960e
* Content: [API Collecte de données HTTP Azure Monitor](https://docs.microsoft.com/fr-fr/azure/azure-monitor/platform/data-collector-api#feedback)
* Content Source: [articles/azure-monitor/platform/data-collector-api.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/azure-monitor/platform/data-collector-api.md)
* Service: **azure-monitor**
* Sub-service: **logs**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by srvbpigh** [comment]
Hello, @JamesDLD
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JamesDLD 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continually improve your experience.

Kind regards,
Microsoft DOCS International Team

**Comment by JamesDLD** [comment]
With pleasure, i just published a story about one use case with this script for info "[Write Custom Logs on Log Analytics through Databricks on Azure](https://link.medium.com/tr1fkdYO92 )"
