### ISSUE TITLE
Erreur concernant facsimileTelephoneNumber

### ISSUE THREAD

**Issue by SweetyNico** [MicrosoftDocs/azure-docs.fr-fr#667]
Dans la rubrique Teams et Skype for Business Online, l'attribut est coché pour les groupes alors que cet ne concerne que les utilisateurs et les contacts

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e7abde7c-df25-bd14-574c-92858daed39d
* Version Independent ID: 6652a5bc-4985-d45e-36fb-54da408e5e54
* Content: [Attributs synchronisés par Azure AD Connect](https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized#feedback)
* Content Source: [articles/active-directory/hybrid/reference-connect-sync-attributes-synchronized.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/hybrid/reference-connect-sync-attributes-synchronized.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @SweetyNico
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @SweetyNico,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/45226.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
