### ISSUE TITLE
Typo error fileHost=$(echo $fileHost | tr -d "/") instead of fileHost=$(echo $smbPath | tr -d "/")

### ISSUE THREAD

**Issue by ados1991** [MicrosoftDocs/azure-docs.fr-fr#669]
Hi,

There is error in the last line of commands below:

# This command assumes you have logged in with az login
httpEndpoint=$(az storage account show \
    --resource-group $resourceGroupName \
    --name $storageAccountName \
    --query "primaryEndpoints.file" | tr -d '"')
smbPath=$(echo $httpEndpoint | cut -c7-$(expr length $httpEndpoint))
fileHost=$(echo $fileHost | tr -d "/")

We are excepting fileHost=$(echo $smbPath | tr -d "/") 

Thanks,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8d60d83f-0094-6c5e-e105-712c24bf1acc
* Version Independent ID: 594af294-fd5d-a8c7-d456-6d753b7b62f8
* Content: [Utiliser Azure Files avec Linux](https://docs.microsoft.com/fr-fr/azure/storage/files/storage-how-to-use-files-linux#feedback)
* Content Source: [articles/storage/files/storage-how-to-use-files-linux.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/storage/files/storage-how-to-use-files-linux.md)
* Service: **storage**
* Sub-service: **files**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by srvbpigh** [comment]
Hello, @ados1991
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @ados1991,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/45721.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
