### ISSUE TITLE
Licences 

### ISSUE THREAD

**Issue by CallMeByMyName** [MicrosoftDocs/azure-docs.fr-fr#670]
Bonjour,

La fonction nécessite de l'Azure AD Preminum 1 ou 2.

La donc dit 1 la consoler Azure dit 2...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: ffdaa549-8f3b-75e0-9d27-a1a10417d86b
* Version Independent ID: aff533db-3ac6-5f9a-0134-812f7d488670
* Content: [Qu’est-ce que l’accès conditionnel dans Azure Active Directory ?](https://docs.microsoft.com/fr-fr/azure/active-directory/conditional-access/overview)
* Content Source: [articles/active-directory/conditional-access/overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/conditional-access/overview.md)
* Service: **active-directory**
* Sub-service: **conditional-access**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @CallMeByMyName
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @CallMeByMyName,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/45884.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
