### ISSUE TITLE
Is it really a more secure manner to connect to other Azure services?

### ISSUE THREAD

**Issue by JamesDLD** [MicrosoftDocs/azure-docs.fr-fr#674]
Hello,

Data Factory is now a 'Trusted Service' in Azure Storage and Azure Key Vault firewall, we can connect to those services as ‘Trusted Service’ using the Data Factory managed identity and the firewall settings ‘Allow trusted Microsoft Services…’.  

Could you please explain why using "service endpoints is more secure" that using 'Trusted Service'?

Reference : https://techcommunity.microsoft.com/t5/azure-data-factory/data-factory-is-now-a-trusted-service-in-azure-storage-and-azure/ba-p/964993

Regards,
James Dumont le Douarec

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93bd5c16-e0ec-5064-9bc0-1c527c328a7e
* Version Independent ID: 5342d01e-c2da-f7a8-d22e-86995a17af79
* Content: [Déployer Azure Databricks dans votre réseau virtuel Azure (injection de réseaux virtuels)-Azure Databricks](https://docs.microsoft.com/fr-fr/azure/databricks/administration-guide/cloud-configurations/azure/vnet-inject)
* Content Source: [databricks/administration-guide/cloud-configurations/azure/vnet-inject.md](https://github.com/MicrosoftDocs/databricks-pr.fr-FR/blob/live/databricks/administration-guide/cloud-configurations/azure/vnet-inject.md)
* Service: **azure-databricks**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by srvbpigh** [comment]
Hello, @JamesDLD
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @JamesDLD,

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by JamesDLD** [comment]
Ok I did it here : https://feedback.azure.com/forums/909463-azure-databricks/suggestions/39483160-security-level-when-connecting-databricks-to-other
