### ISSUE TITLE
2 errors while trying this

### ISSUE THREAD

**Issue by titiks** [MicrosoftDocs/azure-docs.fr-fr#675]
Hello,

1. Error during the task "Azure DevTest Labs Create VM". I'm using version 3.* (preview) of the task. The error message is :

Error =&gt; code: 'InvalidDeploymentParameterValue'; message = 'The value of deployment parameter 'AsPlainText' is null. Please specify the value or use the parameter reference. See https://aka.ms/resource-manager-parameter-files for details.'

So when putting "-newVMName '$(vmName)' -userName '$(userName)' -password (ConvertTo-SecureString -String '$(password)' -AsPlainText -Force)" in the field "template parameters" of the task, AsPlainText is interpreted as a parameter of the template.
I couldn't find a syntax to use it as a parameter of ConvertTo-SecureString.

Yet, I realized that ConvertTo-SecureString is not necessary and that I simply could use -password '$(password)'

2. Error when executing the script GetLabVMParams.ps. I'm using version 4.* of the Azure Powershell task. I left the default output variable for the lab vm Id in the previous step, so passing the Script Argument -labVmId '$(labVMId)' to the powershell task returned this error :

[error]MissingSubscription : The request did not have a subscription or a valid tenant level resource provider.

I then gave the Reference Name "vm" for the output variable in the previous task and then passed the Script Argument -labVmId '$(vm.labVmId)' and it worked.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 8e914d98-f574-d5a2-ee07-cc24b2886365
* Version Independent ID: 05b7ff7f-2edf-3b0f-092c-3cdff7ee1236
* Content: [Intégrer Azure DevTest Labs à votre pipeline de livraison et d’intégration continue d’Azure Pipelines](https://docs.microsoft.com/fr-fr/azure/lab-services/devtest-lab-integrate-ci-cd#feedback)
* Content Source: [articles/lab-services/devtest-lab-integrate-ci-cd.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/lab-services/devtest-lab-integrate-ci-cd.md)
* Service: **lab-services**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by srvbpigh** [comment]
Hello, @titiks
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46475](https://github.com/MicrosoftDocs/azure-docs/issues/46475) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @titiks,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/46475.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International

**Comment by srvbpigh** [comment]
Hello, @titiks, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46475. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
