### ISSUE TITLE
Translate 

### ISSUE THREAD

**Issue by GillesBodart** [MicrosoftDocs/azure-docs.fr-fr#676]
On the french translation  "le mot fair est un" doesn't mean anything as "juste" is differant than "foire"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2757f4d9-e2da-21e8-b8aa-22e86ba9af21
* Version Independent ID: 92ffdebd-e37b-81ff-dc65-ed95b5763279
* Content: [Bons exemples d’énoncés - LUIS - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/luis/luis-concept-utterance#feedback)
* Content Source: [articles/cognitive-services/LUIS/luis-concept-utterance.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/LUIS/luis-concept-utterance.md)
* Service: **cognitive-services**
* Sub-service: **language-understanding**
* GitHub Login: @diberry
* Microsoft Alias: **diberry**

**Comment by srvbpigh** [comment]
Hello, @GillesBodart
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @GillesBodart,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/fr-fr/azure/cognitive-services/luis/luis-concept-utterance#feedback.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
