### ISSUE TITLE
Journaux d’activité ne fonctionnent toujours pas

### ISSUE THREAD

**Issue by gtrennert** [MicrosoftDocs/azure-docs.fr-fr#678]
J'ai déjà essayé azure il y a un an - et je decouvre le même bug catastrophique qu'à l'époque
Le journal repete :
 Se reconnecter  Copier les journaux  Suspendre  Effacer  Développer
Welcome, you are now connected to log-streaming service. ...
No new trace in the past 1 min(s).
No new trace in the past 1 min(s).
No new trace in the past 1 min(s).
C'est hallucinant de proposer un outil dans un état tellement dégradé
J'imagine qu'en payant un abonnenment gold on n'a pas le même souci - quoique ...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 6cf91d8c-d16b-346d-759b-f3c787dea2e5
* Version Independent ID: 7e422baf-0a19-dded-ee83-a71b1c819f2f
* Content: [Créer votre première fonction serverless à partir du portail Azure](https://docs.microsoft.com/fr-fr/azure/azure-functions/functions-create-first-azure-function#feedback)
* Content Source: [articles/azure-functions/functions-create-first-azure-function.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/azure-functions/functions-create-first-azure-function.md)
* GitHub Login: @agschi

**Comment by srvbpigh** [comment]
Hello, @gtrennert
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @gtrennert,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/46643.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
