### ISSUE TITLE
Possibility to define different lockout threshold for each type of counter (familiar / unfamiliar) ?

### ISSUE THREAD

**Issue by bsocca** [MicrosoftDocs/azure-docs.fr-fr#680]
Hello, 

Could you confirm that the Azure AD threshold is used both for familiar and unfamiliar locations ?
If yes, do you have a roadmap to be able to configure independant threshold (existing feature in ADFS 2019) ? 
Regards,

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 9c7b90ca-a2b1-9cd8-9769-cd48c27f10ea
* Version Independent ID: b8c29389-c435-b2f0-4186-1e9c47ab4f3e
* Content: [Prévention des attaques avec le verrouillage intelligent - Azure Active Directory](https://docs.microsoft.com/fr-fr/azure/active-directory/authentication/howto-password-smart-lockout)
* Content Source: [articles/active-directory/authentication/howto-password-smart-lockout.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/authentication/howto-password-smart-lockout.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by srvbpigh** [comment]
Hello, @bsocca
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47075](https://github.com/MicrosoftDocs/azure-docs/issues/47075) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @bsocca, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47075. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
