### ISSUE TITLE
Erreur dans la doc - kubectl get nodes retourne 1 node au lieu de 2.

### ISSUE THREAD

**Issue by couscousbzh** [MicrosoftDocs/azure-docs.fr-fr#681]
Bonjour,

Juste pour signaler une petite erreur dans la doc, lorsque l'on liste les nodes avec la commande kubectl get nodes le résultat doit nous donner 2 nodes et non 1 comme indiquer dans la doc. 

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d4af71a4-648e-580f-7e86-94ce05196de5
* Version Independent ID: 134b8ba0-b085-076a-d2e1-16d0ddff5586
* Content: [Didacticiel Kubernetes sur Azure – Déployer un cluster](https://docs.microsoft.com/fr-fr/azure/aks/tutorial-kubernetes-deploy-cluster#feedback)
* Content Source: [articles/aks/tutorial-kubernetes-deploy-cluster.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/tutorial-kubernetes-deploy-cluster.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @couscousbzh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47162](https://github.com/MicrosoftDocs/azure-docs/issues/47162) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @couscousbzh,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/47162.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
