### ISSUE TITLE
Gestion de Private Link via le portail Azure

### ISSUE THREAD

**Issue by jebontems** [MicrosoftDocs/azure-docs.fr-fr#682]
Bonjour,
Dans les limites, il est indiqué: "La création et la gestion ne sont pas possibles sur le portail Azure."
Cependant, une page propose:"Démarrage rapide : Créer un service Private Link avec le portail Azure"

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: fb4b8145-27ae-8817-6d85-969aa85e601d
* Version Independent ID: 00f897cd-5c20-cb3b-9c17-5f75eddd1715
* Content: [Qu’est-ce que le service Azure Private Link ?](https://docs.microsoft.com/fr-fr/azure/private-link/private-link-service-overview#feedback)
* Content Source: [articles/private-link/private-link-service-overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/private-link/private-link-service-overview.md)
* Service: **private-link**
* GitHub Login: @malopMSFT
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @jebontems
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour, @jebontems 

Nous vous remercions sincèrement pour votre commentaire et nous nous efforçons d’améliorer votre expérience dans docs.microsoft.com. Cependant, nous avons besoin de plus d’informations pour pouvoir répondre à vos commentaires. Pouvez-vous fournir des informations plus détaillées et clarifier votre commentaire ?

Cordialement,
L’équipe internationale Microsoft DOCS

**Comment by jebontems** [comment]
Bonjour,
J'ai donc ces informations contradictoires:
![Limites Private LInk](https://user-images.githubusercontent.com/60966496/74415059-ec732a80-4e42-11ea-84ba-790ec725a34c.JPG)
et
![Portail Private LInk](https://user-images.githubusercontent.com/60966496/74415117-0876cc00-4e43-11ea-9c07-6ea6a2706a23.JPG)
Quelle est l'information correcte?

**Comment by jebontems** [comment]
Bonjour,
Je me suis trompé de bouton: voici donc les infos:
J'ai donc ces informations contradictoires:
Limites Private LInk
et
Portail Private LInk
Quelle est l'information correcte?

**Comment by ticianaciminari** [comment]
Hello @jebontems,

Thank you for your feedback.

We noticed source and target contents have been updated. Now, there are three bullet points, instead of five. Could you please check if your issue still reproduces?

Kind regards,
Microsoft DOCS International Team

#please-translate

**Comment by jebontems** [comment]
Hello,

It is now coherent thank you.
