### ISSUE TITLE
Traduction incorrecte

### ISSUE THREAD

**Issue by Benj-Ch** [MicrosoftDocs/azure-docs.fr-fr#683]
La documentation française indique "Si les serveurs Edge du point de présence disposent du fichier dans leur cache, le POP demande le fichier au serveur d’origine." est en anglais "If no edge servers in the POP have the file in their cache,".

La traduction française devrait être "Si aucun serveur Edge du point de présence ne disposent du fichier dans leur cache,".

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e157e073-fc7c-9593-055c-7187e808e0ae
* Version Independent ID: a608309d-7588-e6a5-882e-0fe2fd275a09
* Content: [Qu’est-ce qu’un réseau de distribution de contenu (CDN) ? - Azure](https://docs.microsoft.com/fr-fr/azure/cdn/cdn-overview#feedback)
* Content Source: [articles/cdn/cdn-overview.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cdn/cdn-overview.md)
* Service: **azure-cdn**
* GitHub Login: @mdgattuso
* Microsoft Alias: **magattus**

**Comment by srvbpigh** [comment]
Hello, @Benj-Ch
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
