### ISSUE TITLE
az CLI exemple KO

### ISSUE THREAD

**Issue by xmoulin** [MicrosoftDocs/azure-docs.fr-fr#684]
"az iot hub device-twin" or "az iot hub invoke-device-method" 

az iot hub: 'invoke-device-method' is not in the 'az iot hub' command group. See 'az iot hub --help'. If the command is from an extension, please make sure the corresponding extension is installed. To learn more about extensions, please visit https://docs.microsoft.com/en-us/cli/azure/azure-cli-extensions-overview

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 25e0932f-9b86-d0bd-a297-5941214e3190
* Version Independent ID: f7df034f-745e-cc49-755b-bf8836eb1844
* Content: [Vérifier la connectivité des appareils dans Azure IoT Hub](https://docs.microsoft.com/fr-fr/azure/iot-hub/tutorial-connectivity#feedback)
* Content Source: [articles/iot-hub/tutorial-connectivity.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/iot-hub/tutorial-connectivity.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @xmoulin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by xmoulin** [comment]
Sorry, I found my error. may just add somewere:

_Note: You will need to have the IoT Hub extension installed in your cloud shell. If you do not have this extenstion you can install it by running the following command.

az extension add --name azure-cli-iot-ext_

**Comment by xmoulin** [comment]
Youps... it's already in the introduction... Sorry for the waste of time :'o(
