### ISSUE TITLE
AKS upgrade best practices

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-docs.fr-fr#685]
From the documentation, it seems that in-place upgrade is a simple and recommended solution. But upgrade can fail and corrupt the master, it can take a long time.

In parallel, in Microsoft conferences, speakers always speak about doing blue/green cluster upgrade, instead of in-place. Should not the B/G option explained in the documentation or do we expect that in-place upgrade is fail-safe and recommended for production-grace workflows ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 7010bd58-42b1-5c90-3253-05deed855be8
* Version Independent ID: c890efb2-cdaf-a3eb-d54f-0e7ccbd4314d
* Content: [Mise à jour d’un cluster Azure Kubernetes Service (AKS)](https://docs.microsoft.com/fr-fr/azure/aks/upgrade-cluster)
* Content Source: [articles/aks/upgrade-cluster.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/upgrade-cluster.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @lgmorand
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @lgmorand, 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team

**Comment by lgmorand** [comment]
@ticianaciminari 
"Our team can only answer feedback related to the documentation." => that's exactly what I'm talking about, first word of my message. to fix the documentation page which can be improved

"Please kindly log your product feedback by using the button " That's also **EXACTLY** what I did (see capture below). So since I followed the feedback button present on the documentation page (which is meant for), please reopen the issue and let's discuss how we can improve OUR documentation for OUR customers ;-)

thanks
![bug](https://user-images.githubusercontent.com/6757079/74908234-a4f61c80-53b5-11ea-9bdc-10c9621ec1fc.png)

**Comment by lgmorand** [comment]
@ticianaciminari @CeciAc no news ? Could you tell me why the issue has been closed when I just followed up directions ?
