### ISSUE TITLE
Details on Silent SSO - tenant ID

### ISSUE THREAD

**Issue by bsocca** [MicrosoftDocs/azure-docs.fr-fr#687]
Hello, 
In the document you indicate : "Users also get a silent sign-on experience if an application (for example, https://contoso.sharepoint.com) sends sign-in requests to Azure AD's endpoints set up as tenants - that is, https://login.microsoftonline.com/contoso.com/&lt;..&gt; or https://login.microsoftonline.com/&lt;tenant_ID&gt;/&lt;..&gt;"
==&gt; Could you give some more precisations about the tenant ID ? Do you mean Azure AD ID tenant ?
==&gt; If we manage multiple domains in our Azure AD tenant (contoso.com as managed domain and fabrikam.com as federated domain), could you confirm the behavior if the Azure AD ID tenant ? Does the seamless SSO's feature work for the contoso.com domain in this special case ?

Thanks

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 2010f5ac-1080-addd-1fb3-5b05db26c1f6
* Version Independent ID: 1aa18d6a-5846-7989-b844-fc8ad027921b
* Content: [Azure AD Connect : Authentification unique transparente](https://docs.microsoft.com/fr-fr/azure/active-directory/hybrid/how-to-connect-sso)
* Content Source: [articles/active-directory/hybrid/how-to-connect-sso.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/hybrid/how-to-connect-sso.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @bsocca
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @bsocca, 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team
