### ISSUE TITLE
Get or refresh token from /.auth/ require a setting

### ISSUE THREAD

**Issue by jhauray** [MicrosoftDocs/azure-docs.fr-fr#688]
Il serait intéressant de préciser qu'utiliser les points de terminaison `/.auth/me` et `/.auth/refresh`, nécessite d'activer l'option **Magasin de jetons**, dans le menu "Web App&gt;Authentification / Autorisation".
It could be interesting to precise that using `/.auth/me` and `/.auth/refresh` endpoints, require to enable **Token store** option, in Web App&gt;Authentication settings.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d4518495-4e07-ce2e-4045-5a50b7922b55
* Version Independent ID: 034d1ba0-a737-21ab-3717-ed8798ac5fe1
* Content: [Utilisation avancée de l’authentification/autorisation](https://docs.microsoft.com/fr-fr/azure/app-service/app-service-authentication-how-to#feedback)
* Content Source: [articles/app-service/app-service-authentication-how-to.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/app-service/app-service-authentication-how-to.md)

**Comment by srvbpigh** [comment]
Hello, @jhauray
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49970](https://github.com/MicrosoftDocs/azure-docs/issues/49970) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @jhauray,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/49970.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
