### ISSUE TITLE
What is a selective storage account in Azure?

### ISSUE THREAD

**Issue by jebontems** [MicrosoftDocs/azure-docs.fr-fr#689]
Hello,

I have a question regarding this topic:

Security charges for selective storage accounts will start on January 1, 2020

In https://azure.microsoft.com/en-us/pricing/details/security-center/

What  is a selective storage account in Azure?

Best regards

**Comment by srvbpigh** [comment]
Hello, @jebontems
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Bonjour @jebontems ,  

Merci pour votre contribution. Notre équipe peut uniquement répondre au feedback qui porte sur la documentation.  

Pour envoyer vos commentaires produit, nous vous invitons à cliquer sur le bouton « Envoyer des commentaires sur le produit » situé au bas de la page Docs.  

Si vous avez des commentaires sur la documentation, n’hésitez pas à nous les envoyer via ce canal.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  

L’équipe Microsoft DOCS International
