### ISSUE TITLE
Changing the VNet of an existing Azure Databricks workspace is not supported.

### ISSUE THREAD

**Issue by JamesDLD** [MicrosoftDocs/azure-docs.fr-fr#690]
Would you mind adding in this page as a Known issue that "Changing the VNet of an existing Azure Databricks workspace is not supported".
I did raise a feature request here would appreciate your vote : https://feedback.azure.com/forums/909463-azure-databricks/suggestions/39884620-support-changing-the-vnet-address-space-or-subnet

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93bd5c16-e0ec-5064-9bc0-1c527c328a7e
* Version Independent ID: 5342d01e-c2da-f7a8-d22e-86995a17af79
* Content: [Déployer Azure Databricks dans votre réseau virtuel Azure (injection de réseaux virtuels)-Azure Databricks](https://docs.microsoft.com/fr-fr/azure/databricks/administration-guide/cloud-configurations/azure/vnet-inject)
* Content Source: [databricks/administration-guide/cloud-configurations/azure/vnet-inject.md](https://github.com/MicrosoftDocs/databricks-pr.fr-FR/blob/live/databricks/administration-guide/cloud-configurations/azure/vnet-inject.md)
* Service: **azure-databricks**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by srvbpigh** [comment]
Hello, @JamesDLD
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #49889](https://github.com/MicrosoftDocs/azure-docs/issues/49889) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @JamesDLD, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/49889. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
