### ISSUE TITLE
Can't run Add-RdsAccount

### ISSUE THREAD

**Issue by tbolon** [MicrosoftDocs/azure-docs.fr-fr#692]
When running `Add-RdsAccount -DeploymentUrl "https://rdbroker.wvd.microsoft.com"` I receive the following error: `Add-RdsAccount: One or more errors occurred. (An invalid request URI was provided. The request URI must either be an absolute URI or BaseAddress must be set.)`

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: eab4b2c4-29d9-d759-066f-f7cf633260ca
* Version Independent ID: 05c8b237-2c9e-6453-9cbf-9c7a3b7f8b07
* Content: [Créer un locataire dans Windows Virtual Desktop - Azure](https://docs.microsoft.com/fr-fr/azure/virtual-desktop/tenant-setup-azure-active-directory)
* Content Source: [articles/virtual-desktop/tenant-setup-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/virtual-desktop/tenant-setup-azure-active-directory.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @tbolon
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @tbolon 

Your contribution is highly appreciated. Yet, this feedback is related with product, please kindly log your suggestion by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.

We truly appreciate your contribution to our articles.

Microsoft DOCS International Team

**Comment by tbolon** [comment]
@CeciAc I am not sure that it's a 'feedback'.

I wanted to point the author that, as is, the documentation is incorrect, since the command I ran was the one suggested in the documentation in the section [Create a Windows Virtual Desktop tenant](https://docs.microsoft.com/en-us/azure/virtual-desktop/tenant-setup-azure-active-directory#create-a-windows-virtual-desktop-tenant). And based on the error, it seems that it's the documentation which is wrong (and not the product).

**Comment by tbolon** [comment]
Because this issue is a duplicate of the #29895 on the docs repo, you can retain this issue as closed (duplicate).

Thank you

**Comment by Heidilohr** [comment]
Hi, @tbolon. Sometimes this error appears when someone runs the cmdlet on a version of PowerShell that isn't supported, Like PowerShell Core 6.x or 7.0. Have you tried running this cmdlet using PowerShell 5.0 or 5.1?

**Comment by tbolon** [comment]
You are right @Heidilohr that was exactly the problem here. See my comment on #29895 about my suggestion to mention that on the doc.
