### ISSUE TITLE
Erreur de traduction

### ISSUE THREAD

**Issue by Eagleseb** [MicrosoftDocs/azure-docs.fr-fr#693]
Authentication est un anglicisme. La traduction est identification ou authentification.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c7b6e2b9-7808-6c9b-101e-e6c49c14e175
* Version Independent ID: 92c38af6-f984-5833-bbee-513c4731ecc5
* Content: [Infrastructure de sécurité - Azure IoT Edge](https://docs.microsoft.com/fr-fr/azure/iot-edge/security#feedback)
* Content Source: [articles/iot-edge/security.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/iot-edge/security.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by srvbpigh** [comment]
Hello, @Eagleseb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Bonjour @Eagleseb,   

Merci pour votre feedback.  

Notre équipe linguistique a examiné vos suggestions de traduction et les a acceptées. Nous avons modifié les articles concernés selon vos suggestions et les avons republiés sur les pages https://docs.microsoft.com/fr-fr/azure/iot-edge/security#feedback du site Docs.   

Votre contribution à nos articles est grandement appréciée. Nous vous encourageons donc à continuer d’envoyer vos commentaires à Microsoft.  

Cordialement,  
L’équipe Microsoft DOCS International
