### ISSUE TITLE
Bonjour ! ai le même problème ! quel est le souci ?Merci de votre aide

### ISSUE THREAD

**Issue by gigarun** [MicrosoftDocs/azure-docs.fr-fr#696]
suis dans un AD classique avec le même problème qui revient régulièrement. 
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c12df6f4-66c0-cef7-b108-91225e87ef1b
* Version Independent ID: 86ef625b-2c5f-e5dc-f72e-f028292cbe9c
* Content: [Résoudre les erreurs d’authentification quand vous utilisez le protocole RDP pour vous connecter à une machine virtuelle Azure](https://docs.microsoft.com/fr-fr/azure/virtual-machines/troubleshooting/troubleshoot-authentication-error-rdp-vm#feedback)
* Content Source: [articles/virtual-machines/troubleshooting/troubleshoot-authentication-error-rdp-vm.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/virtual-machines/troubleshooting/troubleshoot-authentication-error-rdp-vm.md)
* Service: **virtual-machines**
* GitHub Login: @Deland-Han
* Microsoft Alias: **delhan**

**Comment by srvbpigh** [comment]
Hello, @gigarun
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by gigarun** [comment]
application of computer settings...
no way to work

**Comment by gigarun** [comment]
no way to reset no way to restart

**Comment by gigarun** [comment]
reset done on hyper-v server by cmd line : application of computer settings... still active after restarting VMs :-(

**Comment by gigarun** [comment]
may be i'm not in right place for that ? thks for help

**Comment by CeciAc** [comment]
Bonjour @gigarun 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton «Envoyer des commentaires sur le produit» qui se trouve au bas de la page DOCS. 

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal. 

Nous apprécions réellement votre contribution à nos articles. 

L’équipe internationale de Microsoft DOCS
