### ISSUE TITLE
Mistake Virtual Machine creation

### ISSUE THREAD

**Issue by MattDierick** [MicrosoftDocs/azure-docs.fr-fr#698]
In VM creation snippet below

storage_image_reference {
        publisher = "Canonical"
        offer     = "UbuntuServer"
        sku       = "16.04.0-LTS"
        version   = "latest"
    }

"Storage" does not exist. It must be "source"

source_image_reference {
        publisher = "Canonical"
        offer     = "UbuntuServer"
        sku       = "16.04.0-LTS"
        version   = "latest"
    }

It correct in the last snippet (the full snippet). Not the first.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 163088fc-67d3-aa81-26e7-0155f3aaa90c
* Version Independent ID: fafceb81-d8fc-8c20-72e5-b2dddc445f73
* Content: [Démarrage rapide : Utiliser Terraform pour créer une machine virtuelle Linux complète dans Azure](https://docs.microsoft.com/fr-fr/azure/terraform/terraform-create-complete-vm#feedback)
* Content Source: [articles/terraform/terraform-create-complete-vm.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/terraform/terraform-create-complete-vm.md)

**Comment by srvbpigh** [comment]
Hello, @MattDierick
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #50918](https://github.com/MicrosoftDocs/azure-docs/issues/50918) via [**ZenHub**](https://www.zenhub.com/)
