### ISSUE TITLE
Chaîne de suggestions de termes différent de celle de la requête?

### ISSUE THREAD

**Issue by SteveDuchene** [MicrosoftDocs/azure-docs.fr-fr#701]
Dans votre exemple les suggestions de termes :
Une requête commence à être saisie dans le champ de recherche
La chaîne de caractère que la chaîne saisie conditionne les suggestions de termes
Les suggestions de termes de votre exemple commencent par la même chaîne de caractères que la requête saisie

Ma question : est-ce qu’il est possible que les suggestions de termes aient un début de chaine de caractères différent de de la chaîne de caractère de la requête ?

Exemple :
Requête saisie : économie sociale
Suggestions de termes : entreprise sociale ; social business…

Cordialement

Stève Duchêne

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f7d4b6ac-d811-4eed-b270-0c3bbc18fcb8
* Version Independent ID: 7b3dd543-2d1f-8be1-90fc-e28e70b9089b
* Content: [Suggestion de termes de recherche avec l’API Suggestion automatique Bing - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/bing-autosuggest/concepts/get-suggestions)
* Content Source: [articles/cognitive-services/Bing-Autosuggest/concepts/get-suggestions.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/Bing-Autosuggest/concepts/get-suggestions.md)
* Service: **cognitive-services**
* Sub-service: **bing-autosuggest**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @SteveDuchene
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52502](https://github.com/MicrosoftDocs/azure-docs/issues/52502) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @SteveDuchene,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/52502.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
