### ISSUE TITLE
De quoi découlent les conditions d'utilisation présentées ici?

### ISSUE THREAD

**Issue by SteveDuchene** [MicrosoftDocs/azure-docs.fr-fr#704]
Les conditions d’utilisation et d’affichage de l’API Recherche Bing sont importantes à connaitre à ce que je vois. Mais il serait bien d'être plus clair quand à la nature et l'origine des ces conditions : Est-ce que ce sont des conditions légales ou contractuelles? Si elles sont contractuelles est-ce que cette page est un extrait des conditions du contrat entre Microsoft et les personnes qui souscrivent à une licence Azure? ou licence Recherche personnalisées Bing...?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f2942e81-02f8-5b66-49e9-2253a8326327
* Version Independent ID: 365bc7c4-2b92-d063-2f50-be58fb27938d
* Content: [Conditions d’utilisation et d’affichage des API Recherche Bing - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/bing-web-search/use-display-requirements#continuity-of-service)
* Content Source: [articles/cognitive-services/Bing-Web-Search/use-display-requirements.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/Bing-Web-Search/use-display-requirements.md)
* Service: **cognitive-services**
* Sub-service: **bing-web-search**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @SteveDuchene
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52319](https://github.com/MicrosoftDocs/azure-docs/issues/52319) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @SteveDuchene,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/52319.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
