### ISSUE TITLE
Déclaration de confidentialité Microsoft uniquement en anglais?

### ISSUE THREAD

**Issue by SteveDuchene** [MicrosoftDocs/azure-docs.fr-fr#705]
Vous donner le lien hypertexte Déclaration de confidentialité Microsoft. Mais le texte proposé est en anglais. Est-ce que celui-ci existe uniquement en anglais? S'il est disponible dans d'autres langues est-ce que sur la page de Déclaration de confidentialité Microsoft il serait possible d'afficher les autres langues disponibles?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: f2942e81-02f8-5b66-49e9-2253a8326327
* Version Independent ID: 365bc7c4-2b92-d063-2f50-be58fb27938d
* Content: [Conditions d’utilisation et d’affichage des API Recherche Bing - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/bing-web-search/use-display-requirements#feedback)
* Content Source: [articles/cognitive-services/Bing-Web-Search/use-display-requirements.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/Bing-Web-Search/use-display-requirements.md)
* Service: **cognitive-services**
* Sub-service: **bing-web-search**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @SteveDuchene
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 can you please check this issue?
the link forwards the user to the en-us version of the Microsoft Privacy Statement instead of fr-fr
I checked and it looks like the issue also replicates in other locales, too

**Comment by ishasahni1** [comment]
@SteveDuchene the Privacy statement page is localized in French. Can you kindly confirm on your browser settings? I tried with changing my browser setting to French and i can review the page.

https://privacy.microsoft.com/fr-fr/privacystatement

@CeciAc FYI

**Comment by SteveDuchene** [comment]
Merci!
C'est bon, c'est en français aussi sur mon navigateur maintenant. Je ne sais pas pourquoi c'était en anglais avant.
Stève
________________________________
De : Isha Sahni <notifications@github.com>
Envoyé : mardi 14 avril 2020 02:24
À : MicrosoftDocs/azure-docs.fr-fr <azure-docs.fr-fr@noreply.github.com>
Cc : Stève Duchêne <duchene_steve@blanchefeigne.com>; Mention <mention@noreply.github.com>
Objet : Re: [MicrosoftDocs/azure-docs.fr-fr] Déclaration de confidentialité Microsoft uniquement en anglais? (#705)


@SteveDuchene<https://github.com/SteveDuchene> the Privacy statement page is localized in French. Can you kindly confirm on your browser settings? I tried with changing my browser setting to French and i can review the page.

https://privacy.microsoft.com/fr-fr/privacystatement

@CeciAc<https://github.com/CeciAc> FYI

**Comment by ishasahni1** [comment]
@SteveDuchene thank you for confirming, glad it worked.
@CeciAc FYI
