### ISSUE TITLE
Revoir l'exemple en python pour la reconnaissance à partir d'un fichier audio

### ISSUE THREAD

**Issue by abalvet** [MicrosoftDocs/azure-docs.fr-fr#706]
Le code python fourni ne permet pas de réaliser la reconnaissance sur un fichier audio, même en suivant les recommandations de format (audio wav 16 Khz).
J'ai une erreur:
No speech could be recognized: NoMatchDetails(reason=NoMatchReason.InitialSilenceTimeout)

Par ailleurs, en activant la reconnaissance continue:
result = speech_recognizer.start_continuous_recognition() 

J'ai l'erreur: 
Traceback (most recent call last):
  File "azure-from-file.py", line 29, in &lt;module&gt;
    if result.reason == speechsdk.ResultReason.RecognizedSpeech:
AttributeError: 'NoneType' object has no attribute 'reason'

Alors qu'avec le code javascript, ça fonctionne (même fichier, même configuration)...

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: a421fddc-eebd-2ff2-6216-b2a00bbd3fdf
* Version Independent ID: 7d902f9e-4f56-30c9-4a39-7d800f92e088
* Content: [Démarrage rapide : Reconnaître la voix à partir d’un fichier audio – Service Speech - Azure Cognitive Services](https://docs.microsoft.com/fr-fr/azure/cognitive-services/speech-service/quickstarts/speech-to-text-from-file?tabs=linux&pivots=programming-language-python#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-file.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cognitive-services/Speech-Service/quickstarts/speech-to-text-from-file.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @IEvangelist
* Microsoft Alias: **dapine**

**Comment by srvbpigh** [comment]
Hello, @abalvet
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52322](https://github.com/MicrosoftDocs/azure-docs/issues/52322) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Bonjour @abalvet,  

Merci pour votre contribution. Votre feedback porte sur la documentation en langue anglaise.  

Nous l’avons donc transféré au dépôt Anglais. Vous pouvez consulter le statut de votre demande ici : https://github.com/MicrosoftDocs/azure-docs/issues/52322.  

Votre contribution à nos articles est grandement appréciée.   

Cordialement,  
L’équipe Microsoft DOCS International
