### ISSUE TITLE
Is there a way (azure cli, powershell, Graph API) to automate requests to extend role assignment ?

### ISSUE THREAD

**Issue by TechWatching** [MicrosoftDocs/azure-docs.fr-fr#707]
I would like to automatically request for a role assignment extension when I receive a mail telling me that one of my role is going to expired. Indeed it's something I have to do quite often and can take a lot of time when you have multiple roles assigned for different ressources and environments.

I can't find anything on the azure cli or elsewhere to programatically request this extension.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: de486759-f16f-4bd9-5639-2bd9bfe8feb1
* Version Independent ID: 4e26e9ef-0d42-f6b2-3441-f66d99f2aa89
* Content: [Renouveler des attributions de rôles de ressources Azure dans PIM - Azure AD](https://docs.microsoft.com/fr-fr/azure/active-directory/privileged-identity-management/pim-resource-roles-renew-extend)
* Content Source: [articles/active-directory/privileged-identity-management/pim-resource-roles-renew-extend.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/active-directory/privileged-identity-management/pim-resource-roles-renew-extend.md)
* Service: **active-directory**
* Sub-service: **pim**
* GitHub Login: @curtand
* Microsoft Alias: **curtand**

**Comment by srvbpigh** [comment]
Hello, @TechWatching
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53167](https://github.com/MicrosoftDocs/azure-docs/issues/53167) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @TechWatching, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/53167. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
