### ISSUE TITLE
Remove PREVIEW mentions 

### ISSUE THREAD

**Issue by geoffreygeslin** [MicrosoftDocs/azure-docs.fr-fr#709]
This page states that Windows Server nodes are "currently in preview in AKS", which is not true anymore.

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e0fcc83c-c911-4d82-98af-ed8880ca6c4a
* Version Independent ID: 00462d96-9a30-8cef-5932-c99bab237706
* Content: [Concepts : sécurité dans AKS (Azure Kubernetes Service)](https://docs.microsoft.com/fr-fr/azure/aks/concepts-security#feedback)
* Content Source: [articles/aks/concepts-security.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/concepts-security.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @geoffreygeslin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @geoffreygeslin 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @geoffreygeslin

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by geoffreygeslin** [comment]
Since "preview" mentions had now been removed from the page (both "en-us" and translated), I close this issue.

Thank you.
