### ISSUE TITLE
Need some guidance preventing major and breaking Windows node updates ?

### ISSUE THREAD

**Issue by geoffreygeslin** [MicrosoftDocs/azure-docs.fr-fr#710]
AKS helps on getting the latest OS security updates and Kubernetes releases, which is perfectlly fine.

But, as Windows containers and host OS has strict compatibility constraints, i'm wondering how AKS would notify of a MAJOR OS update on Windows nodes image?

As there is no hyperv isolation available for Windows Containers in K8s (so nor in AKS), a container image rebuild is the only way to keep application runnig after such updates, and I want to be sure to anticipate such scenario...

I.E I don't wan't any scale-up, cluster upgrade or redeployment operation to "accidentally" broke my app by provisioning nodes on a new major Windows Server version.

Do I have to prevent this with my "own validation process", providing new (private) nodes, and testing my app runs fine on these ?

Does AKS will provide some special warning before any major Windows Server OS version is beeing pushed as default node image ?

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: e0fcc83c-c911-4d82-98af-ed8880ca6c4a
* Version Independent ID: 00462d96-9a30-8cef-5932-c99bab237706
* Content: [Concepts : sécurité dans AKS (Azure Kubernetes Service)](https://docs.microsoft.com/fr-fr/azure/aks/concepts-security#feedback)
* Content Source: [articles/aks/concepts-security.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/concepts-security.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @geoffreygeslin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54021](https://github.com/MicrosoftDocs/azure-docs/issues/54021) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @geoffreygeslin, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54021. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
