### ISSUE TITLE
French version is not up to date (still using OCP 3.1 and oc openshift)

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-docs.fr-fr#711]
ARO 4.3 is now GA.

localized versions of the doc are not up to date

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: 93aa980e-1970-235c-228a-7b19880171b8
* Version Independent ID: 6f7937a4-12e0-d61c-3bd8-c6347ec48385
* Content: [Tutoriel - Créer un cluster Azure Red Hat OpenShift](https://docs.microsoft.com/fr-fr/azure/openshift/tutorial-create-cluster)
* Content Source: [articles/openshift/tutorial-create-cluster.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/openshift/tutorial-create-cluster.md)
* Service: **container-service**
* GitHub Login: @jimzim
* Microsoft Alias: **jzim**

**Comment by srvbpigh** [comment]
Hello, @lgmorand
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lgmorand

Thank you for your feedback.

The information will be updated as soon as the next translation round is live.

Kind regards,
Microsoft DOCS International Team
