### ISSUE TITLE
Wrong recommendation for the keyvault

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-docs.fr-fr#712]
Flexvolume is deprecated and we should use CSI driver. English version of the doc is up to date, not the french one

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: be1d6d66-150a-fb76-8fca-ef36487acbb7
* Version Independent ID: aa5453d8-6fdd-fbb2-446f-ea63e7ee0955
* Content: [Bonnes pratiques relatives à la sécurité des pods - Azure Kubernetes Service](https://docs.microsoft.com/fr-fr/azure/aks/developer-best-practices-pod-security)
* Content Source: [articles/aks/developer-best-practices-pod-security.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/developer-best-practices-pod-security.md)
* GitHub Login: @zr-msft
* Microsoft Alias: **zarhoads**

**Comment by srvbpigh** [comment]
Hello, @lgmorand
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lgmorand

Thank you for your feedback.

The information will be updated as soon as the next translation round is live.

Kind regards,
Microsoft DOCS International Team

**Comment by lgmorand** [comment]
@CeciAc thanks, could you tell me when it will be please ? for my own culture, to know after how many days/weeks after main doc (EN) updated, is the localized version ready ?

**Comment by lgmorand** [comment]
@CeciAc can I expect an answer ? :)
