### ISSUE TITLE
Wrong recommendation for the keyvault in FAQ

### ISSUE THREAD

**Issue by lgmorand** [MicrosoftDocs/azure-docs.fr-fr#713]
Flexvolume is deprecated and we should use CSI driver. English version of the doc is up to date, not the french one
---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d501ff67-9208-8bcb-e8df-f09e9b16a802
* Version Independent ID: e3fc3851-ddc4-d26c-251d-6ae53d714081
* Content: [Forum aux questions sur Azure Kubernetes Service (AKS)](https://docs.microsoft.com/fr-fr/azure/aks/faq)
* Content Source: [articles/aks/faq.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/aks/faq.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @lgmorand
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @lgmorand

Thank you for your feedback.

The information will be updated as soon as the next translation round is live.

Kind regards,
Microsoft DOCS International Team

**Comment by lgmorand** [comment]
@CeciAc why closing the tickets before the localization is done ? In the (short) past, some translations were missing, because mistakes can happen during localization round. 
Isn't it more careful to keep it open, like a bug (because it's currently a bug giving wrong information to customers), and then close it as soon as the new localization is published ? :)
That's how we manage issues with all our products at Microsoft, I'm little bit surprise that docs doesn't follow good practices <3
