### ISSUE TITLE
geek a fermer mon comte celle que javais mes achat et la ferme sans que ce sois moi qui le demande

### ISSUE THREAD

**Issue by paulette28** [MicrosoftDocs/azure-docs.fr-fr#720]
[Tapez vos commentaires ici]

---
#### Détails du document

⚠ *Ne pas modifier cette section. Elle est requise pour docs.microsoft.com ➟ problème de liaison GitHub.*

* ID: 3f0af130-6b0a-0a7e-5fd9-e67810f66b45
* Version Independent ID: 445b1c77-472a-e0f7-45fc-168f4a2454f3
* Content: [Échanges et remboursements en libre-service de réservations Azure](https://docs.microsoft.com/fr-ca/azure/cost-management-billing/reservations/exchange-and-refund-azure-reservations#how-return-and-exchange-transactions-are-processed)
* Content Source: [articles/cost-management-billing/reservations/exchange-and-refund-azure-reservations.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/cost-management-billing/reservations/exchange-and-refund-azure-reservations.md)
* Service: **cost-management-billing**
* GitHub Login: @yashesvi
* Microsoft Alias: **banders**

**Comment by paulette28** [comment]
jje me suis faite prendre mon pris mon comte  geek sans mon consentement en plus javais une grosse somme tk pour moi sa le comme je peux me faire rembourse la somme au complet

**Comment by paulette28** [comment]
une somme de 1000$ et plus jai jamais rien recu

**Comment by srvbpigh** [comment]
Hello, @paulette28
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Bonjour @paulette28 

Votre contribution est très appréciée. Ces commentaires concernant un produit, nous vous invitons à enregistrer votre suggestion en utilisant le bouton « Envoyer des commentaires sur le produit » qui se trouve au bas de la page DOCS.

Si vous avez des commentaires relatifs à la documentation, n'hésitez pas à les communiquer par ce canal.

Nous apprécions réellement votre contribution à nos articles.

L’équipe internationale de Microsoft DOCS
