### ISSUE TITLE
Problème lien RAW vers github

### ISSUE THREAD

**Issue by fdaschmidt** [MicrosoftDocs/azure-docs.fr-fr#736]
Bonjour,
J'ai effectué votre tutoriel mais au niveau de l'url raw vers le fichier github le problème c'est qu'il devient en 404 au bout d'un lapse de temps (même en enlevant le token) Comment "dans la vra i vie" fait t'on ?

merci par avance, et merci pour la qualité de vos tuto

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: c413ca77-40c2-5ee9-2fbe-ee4334cdf496
* Version Independent ID: 63af751d-c7a8-7a53-fc5c-fc057684d22a
* Content: [Intégration continue avec Azure Pipelines - Azure Resource Manager](https://docs.microsoft.com/fr-fr/azure/azure-resource-manager/templates/deployment-tutorial-pipeline)
* Content Source: [articles/azure-resource-manager/templates/deployment-tutorial-pipeline.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/azure-resource-manager/templates/deployment-tutorial-pipeline.md)
* Service: **azure-resource-manager**
* Sub-service: **templates**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by mumian** [comment]
@fdaschmidt - I assume the error is related to the value you specified for **Override template parameters**.  You can paste the URL in a browser to test it first before you use the value in the parameter.  Use these steps to get the correct URL:

1. Open the GitHub repo in a browser.  The URL is github.com/<your account name>/<your repo name>
2. Select **CreateWebApp**.  You created this folder in the **Clone the remote repository** section.
3. Select **linkedStoraeAccount.json**.  You added this file in the **Download a Quickstart template** section.
4. Select **Raw** right above the actual template. The URL of the page is the URL of the template that you need.

I will close the ticket for now. If you have any further questions, I can reopen the ticket.

#please-close.
