### ISSUE TITLE
Unable to use Inline Code action: Operation failed: template validation failed

### ISSUE THREAD

**Issue by lasyan3** [MicrosoftDocs/azure-docs.fr-fr#748]
Hi, when trying to use Inline Code action, I get this error : Operation failed: The template validation failed: 'Invalid URI: The hostname could not be parsed.'.
![2020-10-09 11_57_00-Logic Apps Designer - Microsoft Azure](https://user-images.githubusercontent.com/7955594/95569984-96cd3d00-0a26-11eb-958c-d27f30df779f.png)

---
#### Détails du document

⚠ *Ne pas modifier cette section. C’est obligatoire pour docs.microsoft.com ➟ Liaison des problèmes GitHub.*

* ID: d660520b-e327-c1e5-e771-692cc9d254e4
* Version Independent ID: d6a8c604-c51a-4d45-e2d9-678665fea0d1
* Content: [Ajouter et exécuter des extraits de code avec du code inline - Azure Logic Apps](https://docs.microsoft.com/fr-fr/azure/logic-apps/logic-apps-add-run-inline-code)
* Content Source: [articles/logic-apps/logic-apps-add-run-inline-code.md](https://github.com/MicrosoftDocs/azure-docs.fr-fr/blob/master/articles/logic-apps/logic-apps-add-run-inline-code.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by SunnyDeng** [comment]
Hi @lasyan3 
Thank you for the feedback! We've transfer this issue to EN repo. Please kindly check the respond in https://github.com/MicrosoftDocs/azure-docs/issues/65838.
